export interface PlantInfo {
  id: string;
  nameTr: string;
  nameEn: string;
  icon: string;
  descTr: string;
  descEn: string;
  healthTr: string;
  healthEn: string;
  ecoTr: string;
  ecoEn: string;
  lifespanTr: string;
  lifespanEn: string;
  waterNeedTr: string;
  waterNeedEn: string;
  regionsTr: string;
  regionsEn: string;
  factTr: string;
  factEn: string;
}

export const FIFTY_PLANTS: PlantInfo[] = [
  // --- MEYVE AĞAÇLARI ---
  {
    id: 'elma',
    nameTr: 'Elma',
    nameEn: 'Apple',
    icon: '🍎',
    descTr: 'Ilıman iklimleri seven, ilkbaharda pembe-beyaz çiçekler açan, yaprak döken popüler bir meyve ağacıdır.',
    descEn: 'A popular deciduous temperate fruit tree blooming with white-pink spring blossoms, yielding crisp global sweet fruits.',
    healthTr: 'Zengin lif, vitamin C ve pektin barındırır; sindirimi kolaylaştırır ve kan şekerini dengeler.',
    healthEn: 'Rich in dietary fiber, Vitamin C, and pectin; aids gut digestion and helps maintain blood sugar levels.',
    ecoTr: 'Yüksek oksijen salınımı yapar ve ilkbahar aylarında polenleriyle yararlı böcekleri çeker.',
    ecoEn: 'Generates great amounts of clean oxygen and feeds early pollinators with its rich spring pollen.',
    lifespanTr: '50 - 100 Yıl',
    lifespanEn: '50 - 100 Years',
    waterNeedTr: 'Orta (Meyve gelişim döneminde düzenli sulama ister)',
    waterNeedEn: 'Medium (Requires standard regular watering during hot summer fruiting season)',
    regionsTr: 'İç Anadolu ve Göller Yöresi',
    regionsEn: 'Central Anatolian orchards and Lakes Region',
    factTr: 'Dünyada 7500\'den fazla kayıtlı elma çeşidi vardır ve bir elma ağacı yılda binlerce meyve verebilir.',
    factEn: 'There are over 7,500 registered apple cultivars globally, and a mature tree produces thousands of apples.'
  },
  {
    id: 'armut',
    nameTr: 'Armut',
    nameEn: 'Pear',
    icon: '🍐',
    descTr: 'Gül ailesinden, sulu ve lifli tatlı meyveler sunan, kış soğuklarına son derece dayanıklı bir meyve ağacıdır.',
    descEn: 'A deciduous tree of the rose family, yielding sweet, grit-textured teardrop-shaped juicy fruits.',
    healthTr: 'Yüksek potasyum ve lif barındırır; tansiyonu düzenler ve böbrek sağlığını destekler.',
    healthEn: 'Boasts high potassium and fiber; assists blood pressure control and supports kidney health.',
    ecoTr: 'Çit zeminlerinde rüzgar süzme gücü yüksektir ve kuşlar için güvenli barınma sağlar.',
    ecoEn: 'Acts as excellent windbreak and provides safe nesting spots for sweet songbirds.',
    lifespanTr: '50 - 80 Yıl',
    lifespanEn: '50 - 80 Years',
    waterNeedTr: 'Orta (Hafif nemli zeminlerde daha lezzetli meyveler verir)',
    waterNeedEn: 'Medium (Yields much juicier harvests in deep, moderately damp soils)',
    regionsTr: 'Marmara ve Ege Bölgeleri',
    regionsEn: 'Marmara and Aegean provinces',
    factTr: 'Armutlar daldan koptuktan sonra olgunlaşmaya devam eden nadir meyvelerdendir, bu sebeple sertken toplanırlar.',
    factEn: 'Pears are among the rare fruits that ripen best off the tree, normally picked green for maximum storage.'
  },
  {
    id: 'portakal',
    nameTr: 'Portakal',
    nameEn: 'Orange',
    icon: '🍊',
    descTr: 'Yapraklarını dökmeyen, kokulu beyaz çiçekleri ve nefis turuncu meyveleri ile göz kamaştıran bir narenciyedir.',
    descEn: 'An evergreen citrus canopy tree yielding iconic sweet round golden globes, filling coasts with beautiful scent.',
    healthTr: 'Zengin C vitamini ve antioksidan deposudur; bağışıklığı güçlendirir ve cildi korur.',
    healthEn: 'An excellent source of Vitamin C and antioxidants; boosts natural immunity and preserves youthful skin.',
    ecoTr: 'Yaprak dökmediği için yıl boyu karbon yakalar; arıcılıkta nektar kaynağı sağlar.',
    ecoEn: 'Provides year-round carbon capture as an evergreen, supplying vital foraging nectar for bee colonies.',
    lifespanTr: '50 - 100 Yıl',
    lifespanEn: '50 - 100 Years',
    waterNeedTr: 'Orta-Yüksek (Toprağı nemli tutulmalıdır, susuz kaldığında meyvesini döker)',
    waterNeedEn: 'Medium-High (Demands constant moisture during hot blooming and fruit-set seasons)',
    regionsTr: 'Akdeniz ve Ege Bölgeleri',
    regionsEn: 'Mediterranean coastlines and Southern Aegean',
    factTr: 'Portakal aslında Çin mandalinası ile greyfurtun binlerce yıl önce doğada yaptığı bir melezlemedir.',
    factEn: 'The sweet orange is actually an ancient hybrid cross between the mandarin and pomelo genomes.'
  },
  {
    id: 'limon',
    nameTr: 'Limon',
    nameEn: 'Lemon',
    icon: '🍋',
    descTr: 'Ekşi sulu şifalı meyveleri olan, kış soğuklarına hassas, her dem yeşil kokulu bir narenciye ağacıdır.',
    descEn: 'A tender evergreen citrus tree prominent in sunny climates, famous worldwide for sour, cleansing fruits.',
    healthTr: 'Vücudu alkali dengesine kavuşturur; karaciğeri arındırır ve sindirimi hızlandırır.',
    healthEn: 'Alkalizes body pH levels, cleanses hepatic pathways, and naturally boosts digestion.',
    ecoTr: 'Zararlı sinekleri esansiyel çit yağlarıyla doğal yoldan ortamdan uzaklaştırır.',
    ecoEn: 'Its fragrant oils naturally repel harmful insect pests from nearby plants.',
    lifespanTr: '50 - 100 Yıl',
    lifespanEn: '50 - 100 Years',
    waterNeedTr: 'Orta-Yüksek (Don havalarını sevmez, düzenli süzülmüş sulama ister)',
    waterNeedEn: 'Medium-High (Extremely sensitive to freezing; requires regular, well-draining watering)',
    regionsTr: 'Doğu Akdeniz Sahili (Mersin, Erdemli)',
    regionsEn: 'East Mediterranean coasts, especially Mersin',
    factTr: 'Tek bir limon ağacı, Akdeniz ikliminde ve iyi bakıldığında yılda 3000 adede kadar limon verebilir.',
    factEn: 'A single mature lemon tree under optimal warm cultivation can produce over 3,000 lemons per year.'
  },
  {
    id: 'kiraz',
    nameTr: 'Kiraz',
    nameEn: 'Cherry',
    icon: '🍒',
    descTr: 'Baharın gelişini pembe-beyaz çiçek şöleniyle duyuran, yazın parlak kırmızı drupa meyveler veren narin bir meyve ağacıdır.',
    descEn: 'A deciduous tree celebrated for incredible spring rose blooms and sweet ruby-colored drupaceous stone fruits.',
    healthTr: 'İçerdiği melatonin hormonu sayesinde uyku kalitesini artırır; kas iltihabını söndürür.',
    healthEn: 'Contains natural melatonin that regulates sleep cycles, and acts as powerful anti-inflammatory for muscles.',
    ecoTr: 'Kuşlar ve arılar için şölen niteliğinde yüksek değerli bir besin istasyonudur.',
    ecoEn: 'Acts as highly beneficial foraging habitat for wild birds and pollinator insects.',
    lifespanTr: '30 - 60 Yıl',
    lifespanEn: '30 - 60 Years',
    waterNeedTr: 'Orta (Kuraklığa orta derecede dayanıklıdır, kökleri nemli killi tın sever)',
    waterNeedEn: 'Medium (Moderately drought-tolerant; prefers deep, aerated moist loamy soils)',
    regionsTr: 'Ege, Marmara ve Göller Yöresi',
    regionsEn: 'Aegean, Marmara, and Lakes Region',
    factTr: 'Japonya\'da kiraz çiçeği festivali (Sakura), yaşamın güzelliğini ve faniliğini sembolize eden milli bir bayramdır.',
    factEn: 'In Japan, cherry blossoms (Sakura) symbolize the fragile, transient nature of life, celebrated during Hanami.'
  },
  {
    id: 'seftali',
    nameTr: 'Şeftali',
    nameEn: 'Peach',
    icon: '🍑',
    descTr: 'Kadifemsi tüylü kabuğu, hoş aroması ve sırılsıklam sulu etiyle bahçelerin gözbebeği olan narin meyve ağacıdır.',
    descEn: 'A small warm-temperate deciduous tree producing fuzzy-skinned, intensely sugary, and juicy stone fruits.',
    healthTr: 'Zengin lif oranı ile sindirim dostudur; beta-karoten ile göz ve cilt sağlığına can suyu olur.',
    healthEn: 'Stuffed with dietary fiber supporting gut health, and rich in beta-carotene for skin and ocular cells.',
    ecoTr: 'Geniş yaprak alanı ile kentsel havayı serinletir ve karbonu hızlıca depolar.',
    ecoEn: 'Cools local atmospheres through high transpiration rates and stores carbon efficiently.',
    lifespanTr: '20 - 40 Yıl',
    lifespanEn: '20 - 40 Years',
    waterNeedTr: 'Orta-Yüksek (Meyvesinin dolgunlaşması süresince düzenli can suyu bekler)',
    waterNeedEn: 'Medium-High (Demands rich soil moisture during active summer fruit-swelling periods)',
    regionsTr: 'Marmara (Bursa) ve Ege Kıyı Ovaları',
    regionsEn: 'Marmara region (Bursa) and coastal Aegean plains',
    factTr: 'Şeftali gül ailesine (Rosaceae) mensuptur; tüysüz olan nektarin ise şeftalinin doğal bir genetik mutasyonudur.',
    factEn: 'Peaches belong to the Rose family; the smooth-skinned nectarine is a natural sport variation of the peach.'
  },
  {
    id: 'mango',
    nameTr: 'Mango',
    nameEn: 'Mango',
    icon: '🥭',
    descTr: 'Tropikal iklimlerin gözbebeği, etli, lezzetli ve egzotik sapsarı meyveler veren heybetli, yaprak dökmeyen bir ağaçtır.',
    descEn: 'A magnificent tropical evergreen tree yielding dense, sweet, highly valued exotic yellow-orange stone fruits.',
    healthTr: 'Aşırı oranda A ve C vitamini barındırır; göz dokusunu onarır ve sindirimi hızlandırır.',
    healthEn: 'Bursting with Vitamins A and C; supports vision health and acts as an enzyme-rich digestive aid.',
    ecoTr: 'Devasa yaprak tacıyla tropikal fırtınaları yumuşatır, rüzgardan aşınmayı önler.',
    ecoEn: 'Its massive dense dome shields local systems from typhoons, preserving delicate forest floors.',
    lifespanTr: '100 - 300 Yıl',
    lifespanEn: '100 - 300 Years',
    waterNeedTr: 'Yüksek (Tropikal iklimlerde bol nem ve düzenli yoğun can suyu ile parlar)',
    waterNeedEn: 'High (Demands abundant year-round moisture and warm tropical thermal ranges)',
    regionsTr: 'Akdeniz Sahil Havzaları (Deneme yetiştiriciliği yapılan sıcak seralar)',
    regionsEn: 'Southeastern warm coastal micro-estuaries of Turkey (experimental hot greenhouses)',
    factTr: 'Hint kültüründe mango yaprakları düğün gibi kutlamalarda uğur getirmesi için evlerin girişine asılır.',
    factEn: 'In Indian culture, mango leaves are strung across doorframes for good luck during sacred wedding rites.'
  },
  {
    id: 'avokado',
    nameTr: 'Avokado',
    nameEn: 'Avocado',
    icon: '🥑',
    descTr: 'Tropikal ve subtropikal nemli kıyıları seven, tek büyük çekirdekli ve kremamsı sağlıklı yağ dolgulu süper besin ağacıdır.',
    descEn: 'A subtropical evergreen tree yielding pear-shaped drupes with a large pit, prized for creamy healthy fats.',
    healthTr: 'Tekli doymamış sağlıklı yağ asitleri ve potasyum deposudur; kalbi ve damar esnekliğini korur.',
    healthEn: 'Abundant in healthy monounsaturated fats and potassium; maintains vascular elasticity and heart health.',
    ecoTr: 'Derin kökleriyle toprağı sıkıca tutar ve kıyı erozyonunu yerinde engeller.',
    ecoEn: 'Holds soil structures firmly with deep root nets, blocking subsoil erosion on coastal slopes.',
    lifespanTr: '80 - 150 Yıl',
    lifespanEn: '80 - 150 Years',
    waterNeedTr: 'Yüksek (Kök bölgesinin düzenli nemli kalmasını, süzülen suları tercih eder)',
    waterNeedEn: 'High (Requires constantly moist under-layers and proper quick-draining organic soil)',
    regionsTr: 'Batı Akdeniz Sahili (Antalya, Alanya, Gazipaşa)',
    regionsEn: 'West Mediterranean coasts (Antalya, Alanya, Gazipasa)',
    factTr: 'Avokadolar ağaç üzerinde asılıyken asla olgunlaşmazlar; dalından koparıldıktan birkaç gün sonra yumuşamaya başlarlar.',
    factEn: 'Avocados never ripen while attached to the tree; they only soften and mature after being harvested.'
  },
  {
    id: 'findik',
    nameTr: 'Fındık',
    nameEn: 'Hazelnut',
    icon: '🌰',
    descTr: 'Güleryüzlü nemli havaları çok seven, besleyici ve sert kabuklu meyveleriyle ünlü çok yıllık çalı formunda bir bitkidir.',
    descEn: 'A deciduous multi-stemmed crop tree that thrives in high-humidity zones, yielding delicious hard-shelled nuts.',
    healthTr: 'Magnezyum, demir ve E vitamini deposudur; beyin fonksiyonlarını korur ve enerji üretimine katkı sağlar.',
    healthEn: 'Rich in magnesium, iron, and Vitamin E; support neural function and provides high sustained daily energy.',
    ecoTr: 'Geniş saçak kök yapısıyla dik ve heyelan riski yüksek yamaçlarda toprağı korur.',
    ecoEn: 'Prevents mountain soil loss and land sliding through its colossal network of fibrous crop roots.',
    lifespanTr: '60 - 100 Yıl',
    lifespanEn: '60 - 100 Years',
    waterNeedTr: 'Yüksek (Karadeniz\'in periyodik yağışlı ve nemli havasını çok sever)',
    waterNeedEn: 'High (Demands evenly dispersed year-round rain and high relative humidity levels)',
    regionsTr: 'Doğu ve Batı Karadeniz Sahili',
    regionsEn: 'Northern Black Sea coastline of Turkey',
    factTr: 'Türkiye, dünya fındık üretiminin ve ticaretinin yaklaşık %70\'ini tek başına karşılamaktadır.',
    factEn: 'Turkey produces and exports around 70% of the entire global commercial hazelnut supply.'
  },
  {
    id: 'hindistancevizi',
    nameTr: 'Hindistan Cevizi',
    nameEn: 'Coconut Palm',
    icon: '🥥',
    descTr: 'Tropikal deniz kenarlarındaki kumlarda yükselen, dev saçak yapraklı ve içinde şifalı sular barındıran dayanıklı palmiyedir.',
    descEn: 'A tropical coastal evergreen palm tree with sweepy fronds, yielding large water-filled fibrous shelled nuts.',
    healthTr: 'Suyu ve yağı harika elektrolitlerle doludur; kas ve mideyi yatıştırır, saç ve cildi canlandırır.',
    healthEn: 'Its nutrient-dense liquid is packed with natural electrolytes, rehydrating muscles and soothing dry skin.',
    ecoTr: 'Deniz rüzgarlarını keserek kıyı bitki örtülerini korur, tuzlu kumlarda can suyu yaratır.',
    ecoEn: 'Mitigates coastal gale wind stress and grows robustly in highly saline, sandy coastal formations.',
    lifespanTr: '85 - 100 Yıl',
    lifespanEn: '85 - 100 Years',
    waterNeedTr: 'Yüksek (Köklerinden tuzlu su alsa da bol nem ve yağmur tazyiki bekler)',
    waterNeedEn: 'High (Thrives in rainy, highly humid islands and warm coastal systems)',
    regionsTr: 'Doğal ortamında Tropikal Adalar (Evde saksı süsü olarak beslenebilir)',
    regionsEn: 'Tropical islands (can only be nurtured indoors as houseplant in Turkey)',
    factTr: 'Hindistan cevizleri denize düştükten sonra aylarca tuzlu su üzerinde batmadan seyahat edip çimlenebilirler.',
    factEn: 'Coconut fruits can float buoyant on oceans for months, germinating perfectly upon washing up on distant sands.'
  },
  {
    id: 'uzum',
    nameTr: 'Üzüm',
    nameEn: 'Grapevine',
    icon: '🍇',
    descTr: 'Asmalar halinde sarmallarla sarılarak tırmanan, salkım salkım sulu meyveler veren çok yıllık odunsu bir tırmanıcıdır.',
    descEn: 'A trailing deciduous woody vine that climbs surfaces with tendrils, producing sugary, sweet hanging clusters.',
    healthTr: 'Çekirdeğinde ve kabuğunda resveratrol barındırır; yaşlanmayı geciktirir ve kan dolaşımını canlandırır.',
    healthEn: 'Loaded with resveratrol in seeds and skin; delays cell aging and improves cardiac blood flow.',
    ecoTr: 'Derin toprak katmanlarına ulaşan kökleriyle yer altı sularının verimli dolaşmasına yardım eder.',
    ecoEn: 'Its incredibly deep taproots balance subterranean moisture distribution and secure dry soils.',
    lifespanTr: '50 - 150 Yıl',
    lifespanEn: '50 - 150 Years',
    waterNeedTr: 'Düşük-Orta (Bir defa köklendikten sonra yaz boyunca kuraklığa çok dirençlidir)',
    waterNeedEn: 'Low-Medium (Extremely resilient against hot summers once its roots establish deep in the ground)',
    regionsTr: 'Ege (Manisa), İç Anadolu ve Güneydoğu Anadolu genelinde',
    regionsEn: 'Aegean (Manisa), Central and Southeastern valleys',
    factTr: 'Kurtuluş tarihi kalıntılarında asma yaprakları ve salkımları bereketi simgeler; taze asma yapraklarından sarma yapılır.',
    factEn: 'Grapevine motifs symbolize abundance in antiquity; young leaves are widely stuffed to make traditional sarma.'
  },

  // --- ORMAN AĞAÇLARI ---
  {
    id: 'cam',
    nameTr: 'Çam',
    nameEn: 'Pine',
    icon: '🌲',
    descTr: 'İğne yapraklı, dört mevsim yeşil kalabilen ve kozalak yapısıyla ormanların yükünü çeken asil bir ağaçtır.',
    descEn: 'A resilient coniferous cone-bearing evergreen tree forming majestic global forest biomes.',
    healthTr: 'Çam havasındaki oksijen ve şifalı fitonsitler solunum yollarını temizler, stresi ve astımı yatıştırır.',
    healthEn: 'Phytoncides in pine scent open bronchial passages, easing anxiety and respiratoric conditions.',
    ecoTr: 'Hava kalitesini inanılmaz temizler; rüzgarlarla taşınan toprağı tutarak erozyonu engeller.',
    ecoEn: 'Greatly purifies local air quality, holding sandy slopes and eliminating severe topsoil erosion.',
    lifespanTr: '100 - 1000 Yıl',
    lifespanEn: '100 - 1,000 Years',
    waterNeedTr: 'Düşük (Kurak ve soğuk kayalık havalara mükemmel dayanır)',
    waterNeedEn: 'Low (Well-adapted to dry, poor rocky landscapes and freezing cold winters)',
    regionsTr: 'Akdeniz, Marmara, Ege ve Karadeniz Yamaçları',
    regionsEn: 'Mediterranean, Marmara, Aegean, and Black Sea mountains',
    factTr: 'Bazı çam ağaçları 4500 yıldan fazla yaşayarak dünyamızdaki en yaşlı canlı organizmalardan kabul edilir.',
    factEn: 'Certain ancient pine trees are over 4,500 years old, holding titles among the oldest living organisms.'
  },
  {
    id: 'mese',
    nameTr: 'Meşe',
    nameEn: 'Oak',
    icon: '🌳',
    descTr: 'Geniş tacı, sağlam odunu ve palamut meyveleriyle bilinen görkemli ve çok dayanıklı bir orman devidir.',
    descEn: 'A monumental deciduous forest giant famous for acorns and outstanding physical wood hardness.',
    healthTr: 'Kabuklarındaki tanenler güçlü bir antiseptiktir; boğaz ağrısına ve cilt yaralarına şifalıdır.',
    healthEn: 'Bark tannins act as a superb natural astringent and antiseptic for sore throats and wounds.',
    ecoTr: 'Böceklerden kuşlara kadar binlerce türe ev sahipliği yaparak olağanüstü biyoçeşitlilik merkezi kurar.',
    ecoEn: 'Sustains unique biodiversity by providing food and shelter to hundreds of species of fauna.',
    lifespanTr: '200 - 1000 Yıl',
    lifespanEn: '200 - 1,000 Years',
    waterNeedTr: 'Orta (Yetişkinlik döneminde yağışlar haricinde nadiren sulama diler)',
    waterNeedEn: 'Medium (Sustains primarily on natural rainfall once mature root systems establish)',
    regionsTr: 'İç Anadolu, Marmara ve Doğu Anadolu',
    regionsEn: 'Central, Marmara, and Eastern Anatolian hillsides',
    factTr: 'Tek bir meşe ağacı, yaşamı boyunca yaklaşık 10 milyon palamut üreterek yaban hayatını tam anlamıyla doyurur.',
    factEn: 'Over its long life, a single oak tree can drop up to 10 million nutritive acorns, feeding local wildlife.'
  },
  {
    id: 'sedir',
    nameTr: 'Sedir',
    nameEn: 'Cedar',
    icon: '🌲',
    descTr: 'Yatay yassı şık dalları ve hoş kokulu odunu ile dağlarda asalet sergileyen iğne yapraklı görkemli bir ağaçtır.',
    descEn: 'An iconic mountain coniferous evergreen with spectacular flat-top horizontal branches and pleasant aromatics.',
    healthTr: 'Yağı zihni sakinleştirir; romatizma ağrılarını ve cilt döküntülerini hızla yatıştırır.',
    healthEn: 'Its therapeutic essential oil calms hyperactive thoughts and eases joint and muscular pain.',
    ecoTr: 'Sert rüzgarlara siper olur; derin kökleriyle dağlık kütlelerde heyelanı kalıcı önler.',
    ecoEn: 'Acts as windbreak on steep rocky hillsides, securing fragile mountain watersheds.',
    lifespanTr: '300 - 1000 Yıl',
    lifespanEn: '300 - 1,000 Years',
    waterNeedTr: 'Düşük-Orta (Bir defa büyüdükten sonra sert kuraklığa çok dayanır)',
    waterNeedEn: 'Low-Medium (Extremely well-adapted to rocky, dry sub-alpine mountain soils)',
    regionsTr: 'Akdeniz Bölgesi (Toros Dağları hattı)',
    regionsEn: 'Mediterranean region, primarily along Taurus Mountains',
    factTr: 'Sedir ağacı gövdesi binyıllarca çürümeden kalabilir, antik Mısır\'da saray yapımında kullanılmıştır.',
    factEn: 'Cedar timber is naturally rot-resistant, historic choice for building temples and ancient ships.'
  },
  {
    id: 'cinar',
    nameTr: 'Çınar',
    nameEn: 'Plane Tree',
    icon: '🌳',
    descTr: 'Ulu dalları, elsi geniş yaprakları ve devasa gövde genişliğiyle asırlar boyu meydanları koruyan efsanevi bir devdir.',
    descEn: 'A massive, long-lived deciduous giant with gorgeous flaking bark and broad hand-shaped leaves.',
    healthTr: 'Kaynatılan yaprakları eklem kireçlenmesine ve şiddetli diz ağrılarına geleneksel bir şifadır.',
    healthEn: 'Traditional plane-leaf decoctions target joint inflammation, joint swelling, and arthritis pain.',
    ecoTr: 'Kentsel kirliliği ve tozu süzerek havalandırır; altına muazzam serin bir ekolojik gölge sunar.',
    ecoEn: 'Traps extensive amounts of urban dust and smog, cooling surrounding concrete structures.',
    lifespanTr: '500 - 1500 Yıl',
    lifespanEn: '500 - 1,500 Years',
    waterNeedTr: 'Orta-Yüksek (Nemli ve yeraltı sularının zengin olduğu dere yataklarını çok sever)',
    waterNeedEn: 'Medium-High (Enjoys deep organic damp soils near rivers or rich valley floors)',
    regionsTr: 'Tüm Türkiye genelinde tarihi meydan ve nehirlerde',
    regionsEn: 'Planted across historical city centers and waterways nationwide',
    factTr: 'Osmanlı İmparatorluğu\'nda çınar fidanı, kurulan hanedanın ömrünü ve kudretini simgelemek için her fetih yerine dikilirdi.',
    factEn: 'Historically, the Ottoman Empire planted young plane trees at municipal centers to define eternity.'
  },
  {
    id: 'kavak',
    nameTr: 'Kavak',
    nameEn: 'Poplar',
    icon: '🌳',
    descTr: 'Akarsu kenarlarında sütün gibi hızla dikine yükselen, hafif hışırdayan yapraklı düzgün gövdeli bir ağaçtır.',
    descEn: 'A fast-growing straight-growing deciduous tree thriving in wetlands, known for light-trembling leaves.',
    healthTr: 'Kabuğundan elde edilen doğal salisin maddesi ağrı kesici ve ateş düşürücü şifa üretir.',
    healthEn: 'Its herbal bark yields salicin, historically brewed as a powerful natural painkiller and fever reducer.',
    ecoTr: 'Hızlı boy atarak karbon emilim aslanı olur; yeraltı sığ sularını biyo-filtre eder.',
    ecoEn: 'Acts as exceptionally fast carbon sink due to high growth rate, filtering groundwater along waterways.',
    lifespanTr: '50 - 150 Yıl',
    lifespanEn: '50 - 150 Years',
    waterNeedTr: 'Yüksek (Su kenarlarını sever; sürekli can suyu ve su kanalları bekler)',
    waterNeedEn: 'High (Thrives on river banks, irrigation canals, and soggy water reservoirs)',
    regionsTr: 'Tüm Türkiye akarsu boyları ve dere yatakları',
    regionsEn: 'Grown near streams, valleys, and river channels across Turkey',
    factTr: 'Kavak yapraklarının rüzgarda melodik sesle oynamasının sebebi yaprak saplarının yassı ve aşırı esnek olmasıdır.',
    factEn: 'The melodic rustle poplars make in slight winds is due to their unique flattened, highly flexible leaf stalks.'
  },
  {
    id: 'kayin',
    nameTr: 'Kayın',
    nameEn: 'Beech',
    icon: '🌳',
    descTr: 'Pürüzsüz gümüşümsü gri gövdesi ve sık yaprak örtüsü ile orman zeminine nurlu bir loşluk katan her mevsim yeşil orman asilidir.',
    descEn: 'A beautiful deciduous forest tree with smooth silver-gray bark and a dense, elegant crown shading woods.',
    healthTr: 'Gövdesinden süzülen katranlar egzama gibi cilt hastalıklarını tedavi eder; antiseptiktir.',
    healthEn: 'Distilled beechwood creosote treats skin diseases, and boasts powerful antiseptic traits.',
    ecoTr: 'Asit süzme yeteneği sayesinde asit yağmurlarını nötralize ederek toprak asitliğini korur.',
    ecoEn: 'Protects fragile soil health by filtering and buffering acidic rainfall with its dense canopy.',
    lifespanTr: '150 - 400 Yıl',
    lifespanEn: '150 - 400 Years',
    waterNeedTr: 'Orta-Yüksek (Nemi yüksek, serin ve killi derin orman topraklarında coşar)',
    waterNeedEn: 'Medium-High (Demands rich humid atmospheres and cold, moisture-retaining soils)',
    regionsTr: 'Kuzey ve Kuzeydoğu Karadeniz Dağlık Ormanları',
    regionsEn: 'Humid mountain forests of Black Sea region',
    factTr: 'Kayın ağaçları köklerindeki mantar ağları yardımıyla diğer kayınlarla besin paylaşır ve adeta yardımlaşır.',
    factEn: 'Beech trees share essential sugars with adjacent sick beeches through subterranean mycorrhizal fungi networks.'
  },
  {
    id: 'ihlamur',
    nameTr: 'Ihlamur',
    nameEn: 'Linden',
    icon: '🌳',
    descTr: 'Kalp şeklindeki yaprakları, sarımsı hoş kokulu şifalı çiçekleri ile tanınan geniş gölgeli asil bir ağaçtır.',
    descEn: 'An elegant deciduous forest tree with heart-shaped foliage and intensely sweet-scented golden spring blossoms.',
    healthTr: 'Çiçeklerinin çayı göğsü yumuşatır, öksürüğü giderir ve doğal bitki sakinleştiricisi vazifesi görür.',
    healthEn: 'Relaxing hot tea brewed from its flowers relieves throat irritation, cold symptoms, and daily anxiety.',
    ecoTr: 'Baharın habercisidir; binlerce kovan arıya zengin bir bal nektar cenneti sunar.',
    ecoEn: 'An outstanding pollen source, supporting hive honey bees to yield premium medicinal linden honey.',
    lifespanTr: '100 - 800 Yıl',
    lifespanEn: '100 - 800 Years',
    waterNeedTr: 'Orta (Nemli, tınlı, iyi süzülmüş derin bahçe topraklarını sever)',
    waterNeedEn: 'Medium (Favors well-aerated, moisture-rich garden soils and moderate summer watering)',
    regionsTr: 'Marmara, Ege ve Karadeniz Kıyı Ormanları',
    regionsEn: 'Coastal forests of Marmara, Aegean, and North Black Sea',
    factTr: 'Avrupa kültüründe ıhlamur köy merkezlerine barışın, sevginin ve adaletin simgesi olarak dikilirdi.',
    factEn: 'In ancient European villages, Linden was planted at public squares representing peace, love, and community justice.'
  },

  // --- ÇİÇEKLER ---
  {
    id: 'gul',
    nameTr: 'Gül',
    nameEn: 'Rose',
    icon: '🌹',
    descTr: 'Kendine has muhteşem kokusu, dikenli zarif dalları ve katmerli kadife yapraklarıyla aşkın ve asaletin kadim çiçeğidir.',
    descEn: 'A globally adored thorny elegant shrub bearing layered velvet-textured beautifully perfumed flowers.',
    healthTr: 'Gül suyu cildi dezenfekte eder, gözenekleri sıkılaştırır; yağı zihne neşe ve huzur frekansı verir.',
    healthEn: 'Pure rosewater acts as excellent facial toner, while rose aromatherapy calms heart rates and lifts mood.',
    ecoTr: 'Mis kokulu polenleriyle bahçelerdeki arı sirkülasyonunu ve tozlaşmayı zirveye taşır.',
    ecoEn: 'Increases garden pollinator counts dramatically with its sweet nectar and aromatic scent.',
    lifespanTr: '10 - 35 Yıl',
    lifespanEn: '10 - 35 Years',
    waterNeedTr: 'Orta (Sabahları doğrudan dibe can suyu diler, yapraklara fıskiye dökülmesini sevmez)',
    waterNeedEn: 'Medium (Demands direct soil hydration; dislikes overhead sprinklers that invite mildew)',
    regionsTr: 'Göller Yöresi (Isparta)',
    regionsEn: 'Lakes Region of Turkey, specially Isparta',
    factTr: 'Isparta gülü sabaha karşı saat 04:00 ile 08:00 arasında, güneş çiçeğin üzerindeki yağı uçurmadan toplanır.',
    factEn: 'Isparta petals are harvested manually by dawn between 4:00 and 8:00 AM to rescue delicate essential oils.'
  },
  {
    id: 'papatya',
    nameTr: 'Papatya',
    nameEn: 'Chamomile',
    icon: '🌼',
    descTr: 'Sarı göbeği, beyaz şık taç yaprakları ile doğallığı ve masumiyeti temsil eden çok yıllık kuraklığa dayanıklı kır çiçeğidir.',
    descEn: 'A delicate perennial field herb featuring daisy-like yellow disc centers and white ray petals representing pureness.',
    healthTr: 'Sindirimi rahatlatır, uykusuzluğu giderir; yağı cilt kızarıklıklarını ve tahrişini yatıştırır.',
    healthEn: 'Naturally soothes stomach cramps, promotes deep sleep, and treats acute skin rashes.',
    ecoTr: 'Yabani otların aşırı büyümesini dengeler ve organik zeminleri kükürtle besler.',
    ecoEn: 'Regulates local weed growth naturally and enriches soils with organic compounds.',
    lifespanTr: '2 - 5 Yıl',
    lifespanEn: '2 - 5 Years',
    waterNeedTr: 'Düşük-Orta (Bir kez tutunduktan sonra kuru kırlarda can suyu olmadan hayatta kalır)',
    waterNeedEn: 'Low-Medium (Superbly drought-hardy once spread across sunny open meadows)',
    regionsTr: 'Tüm Türkiye kırları ve yol kenarları',
    regionsEn: 'Wild plains and dry meadows nationwide',
    factTr: 'Papatya bitkisinin kurutulan kafaları demlendiğinde göz altındaki morlukları ve şişlikleri hızla indiren doğal banyo jeli yerine geçer.',
    factEn: 'Brewed dried chamomile flowers applied as cold compress quickly eliminate under-eye dark circles.'
  },
  {
    id: 'aycicegi',
    nameTr: 'Ayçiçeği',
    nameEn: 'Sunflower',
    icon: '🌻',
    descTr: 'Gün boyunca başını güneşe çeviren, devası sarı taçlı ve lezzetli yağlı çekirdekleri olan neşeli bir bitkidir.',
    descEn: 'A tall annual crop tree famed for giant bright golden-yellow flower heads tracking sun rays.',
    healthTr: 'Zengin E vitamini ve selenyum kaynağıdır; hücrelerin hasar görmesini önleyerek kalbi güçlendirir.',
    healthEn: 'Packed with robust plant Vitamin E and selenium; shields heart tissues and acts as antioxidant.',
    ecoTr: 'Topraktaki radyoaktif döküntüleri ve ağır metalleri emerek toprağı temizlemede (fitoremediasyon) şampiyondur.',
    ecoEn: 'An exceptional bioremediation filter, drawing heavy metals and toxins out of polluted soils.',
    lifespanTr: '1 Yıl',
    lifespanEn: '1 Year',
    waterNeedTr: 'Orta (Büyüme evresinde bol suya gerek duysa da sonrasında kuru sıcağa dayanır)',
    waterNeedEn: 'Medium (Requires standard moisture during leaf-growth but turns highly drought-tolerant in dry heat)',
    regionsTr: 'Trakya Bölgesi ve İç Anadolu Platoları',
    regionsEn: 'Thrace plains and Central Anatolian hillsides',
    factTr: 'Ayçiçeği tomurcukları bizzat heliotropizm yaparak doğu-batı ekseninde güneşi izler, olgunlaşınca doğuya sabitlenir.',
    factEn: 'Immature sunflower buds show heliotropism by following the sun path daily, fixing facing east upon full open.'
  },
  {
    id: 'lale',
    nameTr: 'Lale',
    nameEn: 'Tulip',
    icon: '🌷',
    descTr: 'Zambakgillerden, soğanlı, kadeh şeklinde göz alıcı renklerde çiçekler açan asil ve tarihi bir bahar çiçeğidir.',
    descEn: 'A spectacular spring-flowering bulbous genus featuring striking cup-shaped elegant blooms of many colors.',
    healthTr: 'Yatıştırıcı kozmetik yapımında kullanılır, kaynatılan kökü hafif spazm dindirici etkiye sahiptir.',
    healthEn: 'Used in traditional floral cooling cosmetics, bulb extracts serve in historical remedies to quiet muscle spasms.',
    ecoTr: 'Kış biter bitmez erken uyanan polenleri ile baharın ilk aç böceklerine besin köprüsü kurar.',
    ecoEn: 'Waking up immediately after cold winter, it serves early nourishment to waked garden insects.',
    lifespanTr: '1 - 3 Yıl (Soğanları sökülüp tekrar dikilerek yıllarca canlandırılabilir)',
    lifespanEn: '1 - 3 Years (The bulb replicates soil underground, continuing from generation to generation)',
    waterNeedTr: 'Orta (Bahar uykusundan uyandıktan sonra toprağı nemli tutulmalı, aşırı sulanmamalıdır)',
    waterNeedEn: 'Medium (Keep soil moderately moist during its active spring growth; avoid rotting the bulb)',
    regionsTr: 'Marmara (İstanbul sembolüdür) ve Ege Bölgesi',
    regionsEn: 'Marmara (iconic to Istanbul) and Aegean regions',
    factTr: '17. Yüzyıl Hollanda\'sında lale soğanları o kadar değerlendi ki, bir lale soğanı fiyatına lüks evler satın alınırdı (Lale Çılgınlığı).',
    factEn: 'During the 17th-century "Tulip Mania" in Holland, rare tulip bulbs sold for more than the price of a luxury home.'
  },
  {
    id: 'menekse',
    nameTr: 'Menekşe',
    nameEn: 'Violet',
    icon: '💜',
    descTr: 'Yarı gölgeyi seven, kadifemsi mor yaprakları ve narin boynu ile duygusallığı temsil eden şirin bir saksı efsaneleridir.',
    descEn: 'A sweet shade-loving bedding plant displaying delicate purple velvet-looking petals and deep green heart-point leaves.',
    healthTr: 'Yapraklarındaki salisilat asit sivilceleri söndürür; demlenen çayı boğaz balgamını hızla söker.',
    healthEn: 'Salicylate compounds in violet blades treat acne, and leaf tea acts as natural soothing expectorant.',
    ecoTr: 'Toprak yüzeyine yayılarak malç etkisi yapar, yaz sıcağında toprak neminin buharlaşmasını önler.',
    ecoEn: 'Spreads low on garden floors, creating organic mulch layer that saves soil moisture from drying up too fast.',
    lifespanTr: '2 - 5 Yıl',
    lifespanEn: '2 - 5 Years',
    waterNeedTr: 'Orta (Saksı altından nem ister, yapraklarına su püskürtülürse lekelenir ve çürür)',
    waterNeedEn: 'Medium (Prefers damp bottom-watering; sprinkling water overhead stains its velvet blades)',
    regionsTr: 'Tüm Türkiye genelinde ev içi saksı ve gölgelik bahçelerinde',
    regionsEn: 'Grown as popular low-light houseplant and shaded borders nationwide',
    factTr: 'Menekşe çiçekleri yenilebilir çiçekler sınıfındadır; taze salatalara veya pasta süslerine şifa için taze eklenir.',
    factEn: 'True violets are fully edible, frequently used to garnish gourmet plates, salads, and sweet cakes.'
  },
  {
    id: 'lavanta',
    nameTr: 'Lavanta',
    nameEn: 'Lavender',
    icon: '🌿',
    descTr: 'Mor ince başak şeklinde çiçekler açan, çalılık maki formunda kokusu binyıllarla kalabilen şifalı bir bitkidir.',
    descEn: 'A highly aromatic woody perennial subshrub bearing long, deep violet-scented floral spikes.',
    healthTr: 'Yağı ve çayı sakinlik verir, uykusuzluğu dindirir, saç derisini kepekten ve kaşıntıdan korur.',
    healthEn: 'Its herbal oil induces restorative sleep, eases mental stress, and naturally purifies dry hair scalps.',
    ecoTr: 'Arılar için süper zengin bir polen vahasıdır; sivrisinekleri ve zararlı böcekleri bahçeden uzaklaştırır.',
    ecoEn: 'Acts as fantastic magnet for honeybees while repelling garden flies, ticks, and backyard pests.',
    lifespanTr: '10 - 20 Yıl',
    lifespanEn: '10 - 20 Years',
    waterNeedTr: 'Düşük (Kumlu, kireçli, aşırı süzülen kuru alanlarda susuzluğa çok dirençlidir)',
    waterNeedEn: 'Low (Extremely robust in poor sandy, limestone subsoils; excessive wet borders rot its base)',
    regionsTr: 'Göller Yöresi (Isparta, Keçiborlu) ve Ege',
    regionsEn: 'Isparta, Kuyucak lavender fields and Aegean coasts',
    factTr: 'Antik Romalılar lavantayı banyo sularına, çamaşır dolaplarına mikrop ve koku önleyici en değerli mis koku olarak yerleştirirdi.',
    factEn: 'Ancient Romans added lavender oil to their baths and laundry, deriving name from Latin "lavare" (to wash).'
  },
  {
    id: 'ortanca',
    nameTr: 'Ortanca',
    nameEn: 'Hydrangea',
    icon: '🌸',
    descTr: 'Büyük top şeklinde muhteşem çiçek kurulları açan, asitliğine göre rengini değiştiren gölgelik bahçe çalı çiçeğidir.',
    descEn: 'A shade-loving deciduous garden shrub displaying gigantic ball-shaped stunning flower clusters of varying shades.',
    healthTr: 'Kaynatılan kök özleri eski tıpta böbrek taşı sancılarını dindirmek için kullanılmıştır.',
    healthEn: 'Traditional herbalists brewed specialized root tea to relieve urinary tract heat and kidney stones.',
    ecoTr: 'Dev yaprak yüzeyleriyle su buharlaşmasını dengeler; gölgelik ıslak alanlarda nem süzücü olur.',
    ecoEn: 'Cools garden micro-habitats with wide broad leaves that release ambient water vapor.',
    lifespanTr: '10 - 30 Yıl',
    lifespanEn: '10 - 30 Years',
    waterNeedTr: 'Yüksek (Latince adı "Hydrangea", "Su Kabı" demektir; azıcık ihmal edildiğinde hemen bükülür)',
    waterNeedEn: 'High (Its scientific name "Hydrangea" means "water vessel", reflecting its high water needs)',
    regionsTr: 'Karadeniz Sahil Seridi ve nemli Kuzey Marmara vadileri',
    regionsEn: 'Damp valleys of Black Sea and shaded historic parks of Istanbul',
    factTr: 'Toprak asidik ve kükürtlü ise çiçekleri masmavi açar; kireçli ve alkali ise çiçekleri koyu pembe-kırmızı renk alır.',
    factEn: 'Hydrangea blooms turn rich blue in acidic soils, but shift to bright rose-pink in calcium-alkaline zones.'
  },
  {
    id: 'manolya',
    nameTr: 'Manolya',
    nameEn: 'Magnolia',
    icon: '🌸',
    descTr: 'Büyük, beyaz-krem sapsarı mumsu muazzam çiçekler açan, parlak ve cilalı kalın sönmeyen yapraklı bir ağaçtır.',
    descEn: 'A stately ancient tree displaying immense cup-shaped creamy blossoms and big thick glossy, leathery evergreen leaves.',
    healthTr: 'Kabuklarındaki honokiol maddesi kortizolü düşürür; kaygı ve depresyonu dindiren şifa barındırır.',
    healthEn: 'Honokiol compound in magnolia bark reduces stress hormones, treating moderate panic and mild anxiety.',
    ecoTr: 'Zengin dalları kuş sürülerine kışın rüzgardan sığınacak harika bir yeşil zırh örer.',
    ecoEn: 'Offers pristine year-round shelter for small local winter birds with its strong leathery foliage.',
    lifespanTr: '80 - 150 Yıl',
    lifespanEn: '80 - 150 Years',
    waterNeedTr: 'Orta-Yüksek (Nem dengeli süzülen humuslu killi asidik toprakları çok sever)',
    waterNeedEn: 'Medium-High (Enjoys rich, moist, slightly acidic and well-draining garden soil structures)',
    regionsTr: 'Marmara, Ege ve Akdeniz Nemli Sahil Kesimleri',
    regionsEn: 'Coastal districts across Marmara, Aegean, and Mediterranean regions',
    factTr: 'Fosil kayıtlarına göre dünyada bal arılarından bile önce var oldukları için tozlaşmayı kınkanatlı böceklerle yaparlardı.',
    factEn: 'A fascinating pre-historic tree, magnolias evolved before bees appeared; pollinated originally by beetles.'
  },
  {
    id: 'sakayik',
    nameTr: 'Şakayık',
    nameEn: 'Peony',
    icon: '🌹',
    descTr: 'İçi kat kat tül gibi sarılı devasa şık çiçekleri, gür yeşil çalılığı ile bahçelere saray zarafeti getiren gür bir çiçektir.',
    descEn: 'A highly luxurious perennial herbaceous subshrub blooming with huge ruffled layered tissue-paper-like blossoms.',
    healthTr: 'Kök çayı kan pıhtılaşmasını düzenler; adet sancılarını ve spazmları hafifletir.',
    healthEn: 'Its root tea works on improving active cardiovascular circulation and alleviating systemic muscle cramps.',
    ecoTr: 'Yoğun polenleri tozlaştırıcı sineklerin yuvalanmasını ve bahçenin tozlanmasını destekler.',
    ecoEn: 'Its massive multi-petal cups provide pollen to heavy-weight bumblebees, upgrading pollination yield.',
    lifespanTr: '15 - 50 Yıl',
    lifespanEn: '15 - 50 Years',
    waterNeedTr: 'Orta (Bahar büyümesinde nemli toprak diler, kökünün çamur göllenmesinden hoşlanmaz)',
    waterNeedEn: 'Medium (Demands damp organic soil in spring, but dislikes soggy roots that breed decay)',
    regionsTr: 'Ege ve Karadeniz Dağlık nemli orman altları',
    regionsEn: 'Highland cool zones of Aegean and mountain forests of Black Sea',
    factTr: 'Uzak Doğu sembolizminde şakayık bereketi, gücü, zenginliği ve kraliyet asaletini temsil eden "Çiçeklerin Kralı"dır.',
    factEn: 'In Asian cultures, the Peony represents high wealth and honor, often celebrated as the "King of Flowers."'
  },
  {
    id: 'kasimpati',
    nameTr: 'Kasımpatı',
    nameEn: 'Chrysanthemum',
    icon: '🌼',
    descTr: 'Sonbaharın soğuk günlerinde rengarenk parlayarak bahçeleri neşelendiren dayanıklı bir çiçektir.',
    descEn: 'A hardy late-autumn blooming perennial subshrub displaying densely packed vibrant multi-colored small petals.',
    healthTr: 'Çin tıbbında göz yorgunluğunu dindirir; çayı baş ağrısı, boğaz ateşi ve gripe iyi gelir.',
    healthEn: 'Long used in Chinese medicine, hot flower tea treats eye fatigue, head tension, and early flu cold spikes.',
    ecoTr: 'Havadaki amonyak ve formaldehit gibi zehirli kentsel gazları emmede doğanın usta filtresidir.',
    ecoEn: 'Highly ranked as natural air purifier, drawing hazardous formaldehyde and benzene out of the air.',
    lifespanTr: '5 - 15 Yıl',
    lifespanEn: '5 - 15 Years',
    waterNeedTr: 'Orta (Hafif nemli süzülen zeminleri sever; tomurcukken düzenli can suyu bekler)',
    waterNeedEn: 'Medium (Favors moderately moist soil; requires structured watering throughout its late summer budding season)',
    regionsTr: 'Tüm Türkiye bahçe ve saksıları',
    regionsEn: 'Cultivated in municipal parks and private home balconies nationwide',
    factTr: 'Japonya İmparatorluk ailesinin resmi sembol mührü kasımpatıdır ve ülkede her kasım "Kasımpatı Günü" şerefine şenlenilir.',
    factEn: 'The Chrysanthemum is the royal crest of the Japanese Emperor; the country honors it on National "Festival of Happiness."'
  },

  // --- ŞİFALI BİTKİLER ---
  {
    id: 'nane',
    nameTr: 'Nane',
    nameEn: 'Mint',
    icon: '🌿',
    descTr: 'Ezildiğinde ortama nefis keskin mentol ferahlığı salan, aşırı hızlı yayılan sürüngen gövdeli şifalı bir bitkidir.',
    descEn: 'An herbaceous perennial herb that spreads rapidly, famous for its refreshing, potent menthol aromatic essence.',
    healthTr: 'Sindirimi dindirir; mide bulantısını bıçak gibi keser, solunum yollarını buharıyla derhal açar.',
    healthEn: 'Relieves upset stomachs, completely halts nausea, and clears congested sinuses with natural menthol steam.',
    ecoTr: 'Kuvvetli esansıyla zararlı bahçe sineklerini kaçırırken, çiçekleriyle arılara nektar ikram eder.',
    ecoEn: 'Its volatile oils act as a barrier against agricultural flies while supporting beneficial pollen grids.',
    lifespanTr: '5 - 10 Yıl',
    lifespanEn: '5 - 10 Years',
    waterNeedTr: 'Yüksek (Sürekli ıslak-nemli süzülen toprak ister; kuru kalmaya asla gelemez)',
    waterNeedEn: 'High (Thrives in constantly damp, wet soils; drops and wilts quickly under dry conditions)',
    regionsTr: 'Yar süzülen tüm sulak bahçeler ve dere kenarları',
    regionsEn: 'Grown along streams, damp gardens, and kitchen pots nationwide',
    factTr: 'Nane o kadar arsız ve yayılmacıdır ki, bahçede sınırlandırılmazsa kısa sürede tüm alanı istila edebilir.',
    factEn: 'Mint is so aggressively invasive that its creeping stolons can take over entire garden borders in a season.'
  },
  {
    id: 'kekik',
    nameTr: 'Kekik',
    nameEn: 'Thyme',
    icon: '🌿',
    descTr: 'Güneşli kayalık tepelerde sürünen, minicik yapraklı, kokusu tüm dağları kaplayan son derece güçlü bir Akdeniz maki çiçeğidir.',
    descEn: 'A resilient low-growing evergreen aromatic subshrub packed with thymol, native to hot sunny rocky shores.',
    healthTr: 'Doğal gücü yüksek antiseptik ve antibakteriyeldir; demlenen suyu bronşit ve akciğeri dezenfekte eder.',
    healthEn: 'Rich in thymol, a potent natural antibacterial; relieves dry coughs and sanitizes throat passages.',
    ecoTr: 'Hafif bodur yapısıyla kurak yamaçlarda toprak tuzlanmasını ve toprağın uçmasını engeller.',
    ecoEn: 'Forms dense soil covers on steep slopes, holding fragile topsoil from drying wind sweeps.',
    lifespanTr: '5 - 10 Yıl',
    lifespanEn: '5 - 10 Years',
    waterNeedTr: 'Düşük (Çamurlu kalmayı sevmez; kayalık, kuru ve rüzgarlı sırtlarda susuzlukla coşar)',
    waterNeedEn: 'Low (Drowns in muddy, heavy soils; thrives on barren, stony, wind-swept sunny lands with minimal water)',
    regionsTr: 'Ege ve Akdeniz Kıraç Taşlık Dağları',
    regionsEn: 'Arid rocky hillsides of Aegean and Mediterranean areas',
    factTr: 'Kekikten çıkarılan "kekik yağı", dünyada aranan en güçlü doğal antiviral ve antibakteriyel bitki yağıdır.',
    factEn: 'Essential oil of thyme contains thymol, which was historically used to sanitize surgical tools.'
  },
  {
    id: 'adasayi',
    nameTr: 'Adaçayı',
    nameEn: 'Sage',
    icon: '🌿',
    descTr: 'Kadifemsi gri-yeşil yapraklı, kokusu tütsü gibi tüten, Akdenizli şifalı asil bir maki çalı bitkisidir.',
    descEn: 'A woody perennial evergreen subshrub with velvety grayish-green foliage and powerful antiseptic oils.',
    healthTr: 'Ağız yaralarını, faranjiti ve boğaz ağrısını iyileştirir; soğuk algınlığında mükemmel bir koruyucudur.',
    healthEn: 'Brewed as throat gargle to eliminate oral pathogens, treating laryngitis and winter tonsillitis.',
    ecoTr: 'Erozyon riski olan dağ yamaçlarında toprağın nem tutmasını kolaylaştırır.',
    ecoEn: 'Assists high-altitude slopes in retaining subsoil humidity and organic stability.',
    lifespanTr: '5 - 8 Yıl',
    lifespanEn: '5 - 8 Years',
    waterNeedTr: 'Düşük (Kumlu, kireçli, geçirgen toprağı sever; fazla su köklerini anında çürütür)',
    waterNeedEn: 'Low (Tolerates heavy dry summers; excess stagnant water rots its main roots instantly)',
    regionsTr: 'Ege ve Akdeniz Kıyı Dağları',
    regionsEn: 'Rocky costal mountain ridges across South-Western Turkey',
    factTr: 'Eski uygarlıklarda adaçayı yaprakları tütsü gibi yakılır; odanın havasını mikroplardan temizlemek için duman salınırdı.',
    factEn: 'Historically, burning dried sage bundles (smudging) was used to sterilize air rooms and ward off pests.'
  },
  {
    id: 'biberiye',
    nameTr: 'Biberiye',
    nameEn: 'Rosemary',
    icon: '🌿',
    descTr: 'Cam ağacı yaprağına benzeyen her dem yeşil kokulu yapraklı, mavi çiçekli ve hafızayı artıran şifalı bir çalıdır.',
    descEn: 'An aromatic evergreen needle-like crop shrub with sky-blue blossoms, famous for boosting circulation.',
    healthTr: 'Beyne kan akışını artırarak hafızayı ve odağı güçlendirir; bacak varis ağrılarını hafifletir.',
    healthEn: 'Improves cerebral arterial circulation, enhancing mental focus and dramatically easing muscle fatigue.',
    ecoTr: 'Kurak iklim bahçelerinde rüzgar perdesi kurar; polenleriyle yararlı yaban arılarını besler.',
    ecoEn: 'Acts as fantastic permanent hedge border, supporting wild bumblebees throughout winter.',
    lifespanTr: '15 - 20 Yıl',
    lifespanEn: '15 - 20 Years',
    waterNeedTr: 'Düşük (Kayalık, rüzgarlı sarp dağ kıyılarında az bir can suyu ile yeşil kalır)',
    waterNeedEn: 'Low (Accustomed to marine cliffs; requires very little water once active rooting installs)',
    regionsTr: 'Akdeniz ve Ege Sahil Şeridi',
    regionsEn: 'Coastal cliffs across Mediterranean and Aegean',
    factTr: 'Eski Yunan bilim insanları ve talebeleri, sınavlara çalışırken hafızayı açmak için başlarına biberiye dalları takarlardı.',
    factEn: 'Ancient Greek scholars wore rosemary sprigs in their hair when studying to sharpen their recall.'
  },
  {
    id: 'feslegen',
    nameTr: 'Fesleğen',
    nameEn: 'Basil',
    icon: '🌿',
    descTr: 'Yapraklarına dokunulduğunda cennet gibi keskin baharatlı kokular saçan, tek yıllık sevilen bir Akdeniz rüyasıdır.',
    descEn: 'A highly aromatic annual herb popular in culinary culinary arts, admired for insect-repelling oils.',
    healthTr: 'Sinirleri sakinleştirir, mide şişkinliğini giderir ve sivilceli ciltlere buharıyla şifa olur.',
    healthEn: 'Reduces cortisol tension, naturally cures excess stomach gas, and cleanses congested skin pores.',
    ecoTr: 'Saksıda durduğunda sivrisinek, kara sinek ve zararlı böcekleri kokusuyla ortamdan anında kovar.',
    ecoEn: 'When set on windowsills, it repels mosquitoes and flies, minimizing use of chemical bug sprays.',
    lifespanTr: '1 Yıl',
    lifespanEn: '1 Year',
    waterNeedTr: 'Orta (Sadece dipten sulama ister, yaprakları kuru kalırsa mantardan korunur)',
    waterNeedEn: 'Medium (Requires structured watering exclusively at the soil base to protect blades from powdery mildew)',
    regionsTr: 'Ege ve Akdeniz Sahil Bahçeleri ile mutfak pencereleri',
    regionsEn: 'Grown on sunny balconies and warm kitchen windowsills nationwide',
    factTr: 'Fesleğen yaprağı koparılmadığı sürece kokusunu salmaz; koku kesecikleri yaprağa dokunup çatlatılınca açılır.',
    factEn: 'Basil leaves keep their volatile oils enclosed; they only release fragrance when gently touched or crushed.'
  },
  {
    id: 'aloevera',
    nameTr: 'Aloe Vera',
    nameEn: 'Aloe Vera',
    icon: '🌿',
    descTr: 'Dikenli kenarlı, etli kalın kılıç yapraklı, içinde şifalı jelatinimsi duru öz barındıran asil bir saksı sukulentidir.',
    descEn: 'A stemless evergreen succulent with fleshy thick green blades packing a refreshing, highly therapeutic clear gel.',
    healthTr: 'Yaprak jeli yanıkları, yaraları ve sivrisinek ısırıklarını hızla soğutup onarır; cilde nem yükler.',
    healthEn: 'Raw inner leaf gel provides rapid cooling relief for local sunburns, cuts, and speeds skin healing.',
    ecoTr: 'NASA hava temizleme araştırmalarında odadaki zehirli formaldehit gazını en iyi süzen bitki seçilmiştir.',
    ecoEn: 'Ranked high in NASA Clean Air studies for extracting harmful volatile organic pollutants from houses.',
    lifespanTr: '5 - 12 Yıl',
    lifespanEn: '5 - 12 Years',
    waterNeedTr: 'Düşük (Etli yapraklarında tonlarca su saklar; aşırı sulanırsa sırılsıklam çürür)',
    waterNeedEn: 'Low (Stores copious hydration inside leaf flesh; rots rapidly if roots stay waterlogged)',
    regionsTr: 'Akdeniz sahilleri ve tüm hanelerin aydınlık iç mekanları',
    regionsEn: 'Warm southern shores and bright indoor windowsills everywhere',
    factTr: 'Antik Mısırlılar aloe verayı güzellik ve gençliğin anahtarı görerek ona "Ölümsüzlük Bitkisi" unvanı vermişti.',
    factEn: 'Ancient Egyptians called it "the plant of immortality", using its gel for cosmetics and mummification.'
  },
  {
    id: 'isirganotu',
    nameTr: 'Isırgan Otu',
    nameEn: 'Stinging Nettle',
    icon: '🌿',
    descTr: 'Dokunulduğunda yaprak tüylerindeki formik asit sebebiyle ısıran ancak bütünüyle eşsiz mineral deposu olan otsu bir şifadır.',
    descEn: 'An herbaceous perennial covered in stinging hairs that release formic acid, packed with trace minerals.',
    healthTr: 'Isırgan çayı böbrekleri yıkar, kanı temizler ve ödemi atar; saç köklerini coşturup kepeği bitirir.',
    healthEn: 'Rich infusions flush kidneys, detoxify blood, lower inflammation, and stimulate rapid hair follicle growth.',
    ecoTr: 'Topraktaki fazla azotu bünyesinde emer, toprağın kalitesini ve kireç dengesini yükseltir.',
    ecoEn: 'Clears nitrogen spikes from over-fertilized soils, balancing mineral composition of the soil.',
    lifespanTr: '3 - 8 Yıl',
    lifespanEn: '3 - 8 Years',
    waterNeedTr: 'Orta-Yüksek (Nemli, besince zengin, hafif gölgelik nemli sınır boylarını sever)',
    waterNeedEn: 'Medium-High (Enjoys rich, moist, nitrogen-heavy uncultivated spaces and shaded borders)',
    regionsTr: 'Tüm Türkiye genelinde nemli yol kenarları ve bahçe dipleri',
    regionsEn: 'Common across humid paths, hillsides, and riverbeds nationwide',
    factTr: 'Taze yaprakları pişirildiğinde veya kurutulduğunda asitli tüyleri sönerek tamamen kaybolur ve faydalı bir ıspanak yemeğine dönüşür.',
    factEn: 'Once boiled, steamed, or completely dried, nettle loses its stinging capacity, becoming an iron-rich super vegetable.'
  },

  // --- SEBZELER ---
  {
    id: 'patates',
    nameTr: 'Patates',
    nameEn: 'Potato',
    icon: '🥔',
    descTr: 'Toprak altında nişasta deposu yumrular geliştiren, tüm dünyanın temel besin kaynaklarının başındaki otsu bitkidir.',
    descEn: 'An herbaceous perennial crop that grows starchy, nutritious edible tubers beneath the ground surface.',
    healthTr: 'Yüksek kaliteli kompleks karbonhidrat ve potasyum sağlar; sindirimi kolaylaştırıp mide asidini nötralize eder.',
    healthEn: 'Furnishes rich complex carbohydrates and potassium; calm excess stomach acid and eases digestion.',
    ecoTr: 'Yoğun yaprak örtüsüyle toprağı sımsıkı kaplar, rüzgar esintisinde nem kaybını önler.',
    ecoEn: 'Creates a dense green ground canopy, preserving subterranean soil moisture from sunburn.',
    lifespanTr: '1 Yıl (Yıllık Mahsul)',
    lifespanEn: '1 Year (Annual Crop)',
    waterNeedTr: 'Orta (Yumruların büyümesi için toprak süzülürken düzenli su ister)',
    waterNeedEn: 'Medium (Demands periodic even hydration to develop thick smooth skins on underground tubers)',
    regionsTr: 'İç Anadolu (Nevşehir, Niğde) ve Bolu',
    regionsEn: 'Nevsehir, Nigde, and high mountain soils of Bolu',
    factTr: 'Patates, dünyada uzayda başarıyla yetiştirilen ilk sebzedir (1995 yılında Columbia Uzay Mekiği\'nde).',
    factEn: 'The potato was the first vegetable to be successfully grown in space (aboard Space Shuttle Columbia in 1995).'
  },
  {
    id: 'sogan',
    nameTr: 'Soğan',
    nameEn: 'Onion',
    icon: '🧅',
    descTr: 'Toprak altında kat kat şifalı yumru soğan kuran, yemeklerin sarsılmaz lezzet direği olan iki yıllık soğuk-dayanıklı sebzedir.',
    descEn: 'A biennial bulbous vegetable forming deeply layered, sulfur-rich underground globes, crucial for kitchen arts.',
    healthTr: 'Doğal gücü tescilli antibiyotiktir; kanı dezenfekte eder, solunum tıkanıklıklarını açar ve kalbi korur.',
    healthEn: 'Acts as potent organic antibiotic; boosts vascular elasticity and cleanses internal congestion.',
    ecoTr: 'Köklerinden saldığı kükürtlü gazlar, yandaki sebzelerin mantar hastalıklarına yakalanmasını engeller.',
    ecoEn: 'Releases natural sulfur elements that protect adjacent vegetation from fungal diseases.',
    lifespanTr: '2 Yıl (Meyve hasadı ilk yıl alınır)',
    lifespanEn: '2 Years (Harvested as food within its first annual growth stage)',
    waterNeedTr: 'Düşük-Orta (Baş bağlama aşamasında can suyu diler, sökümden önce sulama kesilmelidir)',
    waterNeedEn: 'Low-Medium (Requires moderate water during bulb sizing; water must be withheld before harvesting)',
    regionsTr: 'İç Anadolu (Ankara, Polatlı) ve Amasya',
    regionsEn: 'Polatli (Ankara), Amasya, and Central Anatolian valleys',
    factTr: 'Soğan doğrarken gözlerimizin yaşarma sebebi, kesilen hücrelerden havaya fırlayan kükürtlü uçucu gazların gözyaşıyla asit yapmasıdır.',
    factEn: 'We cry when slicing onions because volatile sulfur gases combine with eye moisture to yield mild acid.'
  },
  {
    id: 'havuc',
    nameTr: 'Havuç',
    nameEn: 'Carrot',
    icon: '🥕',
    descTr: 'Maydanozgillerden, toprak altında gevrek, tatlı ve turuncu derin kazık kök geliştiren iki yıllık popüler bir sebzedir.',
    descEn: 'A biennial root vegetable with feathery pinnate foliage, growing sweet, crisp, orange-pigmented taproots.',
    healthTr: 'Beta-karoten ve lütein ile doludur; göz retinasını korur ve gece görüş yeteneğini destekler.',
    healthEn: 'Boasts high beta-carotene and lutein; protects eye tissues and enhances night vision.',
    ecoTr: 'Derin kazık kök yapısıyla alt toprak katmanlarını gevşetip havalandırarak toprağı canlandırır.',
    ecoEn: 'Loosens heavy argillaceous soils with deep taproots, improving general aeration for earthworms.',
    lifespanTr: '2 Yıl (Yumru için 1. yıl hasat edilir)',
    lifespanEn: '2 Years (Harvested for food in its first year)',
    waterNeedTr: 'Orta (Sürdürülebilir çatlamayan kazık kökler için nemsiz kalmayan toprağı tercih eder)',
    waterNeedEn: 'Medium (Prefers constant average humidity; dry-wet moisture spikes split the vegetable body)',
    regionsTr: 'İç Anadolu (Konya, Ereğli) ve Beypazarı',
    regionsEn: 'Eregli (Konya), Beypazari (Ankara), and alluvial valleys',
    factTr: 'Havucun asıl kökeni mor ve sarı renkliydi; bugün severek yediğimiz turuncu renkli havuçlar 17. yüzyılda Hollanda\'da türetilmiştir.',
    factEn: 'Carrots were originally purple and yellow; the sweet orange varieties were bred in 17th-century Holland.'
  },
  {
    id: 'misir',
    nameTr: 'Mısır',
    nameEn: 'Corn',
    icon: '🌽',
    descTr: 'Uzun gövdeli, şık şerit yapraklı, püsküllü ve altın sarısı taneli koçanlar veren boylu tek yıllık bir tahıldır.',
    descEn: 'A tall annual cereal plant with robust ribbon blades, producing sweet, golden-grain husked cobs.',
    healthTr: 'Çözünmez lifler barındırır; bağırsak hareketlerini düzenler, B vitaminleriyle beyni besler.',
    healthEn: 'Abundant in insoluble fiber supporting digestive track movements, and packed with energy-giving B vitamins.',
    ecoTr: 'Hızlı büyüme hızı ve boyu sayesinde havadan yüksek oranda karbon hapseder; tarlalara rüzgar perdesi sunar.',
    ecoEn: 'Acts as rapid carbon trap due to dense quick growth, and provides shade shielding lower plants.',
    lifespanTr: '1 Yıl',
    lifespanEn: '1 Year',
    waterNeedTr: 'Yüksek (Püsküllenme ve koçan doldurma aşamasında bol, kesintisiz can suyu ister)',
    waterNeedEn: 'High (Requires heavy irrigation throughout critical pollination and grain-filling stages)',
    regionsTr: 'Karadeniz, Ege ve Çukurova ovaları',
    regionsEn: 'Black Sea coast and coastal Çukurova plains',
    factTr: 'Mısır koçanındaki mısır püskülleri aslında dişi üreme organlarıdır; her bir püskül tek bir mısır tanesine bağlıdır ve döllenir.',
    factEn: 'Each silk strand on a corn ear connects to a single potential kernel, serving as a pollen path.'
  },
  {
    id: 'marul',
    nameTr: 'Marul',
    nameEn: 'Lettuce',
    icon: '🥬',
    descTr: 'Kat kat yumuşak, gevrek ve buzlu yeşil yaprakları olan, diyet salataların sarsılmaz ana çıtır sebzesidir.',
    descEn: 'An annual leafy crop developing overlapping crisp, water-heavy, nested light green tender blades.',
    healthTr: 'Sıfıra yakın kaloriyle %95\'i sudur; vücudu serinletici nemle besler, lifiyle mideyi korur.',
    healthEn: 'Contains 95% water with near-empty calories; rehydrates blood buffers and provides dietary fiber.',
    ecoTr: 'Kısa sürede hasada gelen kök yapısıyla tarla rotasyonunda azot dengesini kurmada etkilidir.',
    ecoEn: 'Grows incredibly fast, ideal for crop rotation and keeping weed expansion restrained in fields.',
    lifespanTr: '1 Yıl (Tek yıllık serin iklim sebzesidir)',
    lifespanEn: '1 Year (Annual cool-season garden leaf)',
    waterNeedTr: 'Yüksek (Yapraklarının gevrek ve sulu kalması için sık sık can suyu diler; susuz kaldığında acılaşır)',
    waterNeedEn: 'High (Demands constant shallow watering; thirst instantly triggers bitter, tough tasting foliage)',
    regionsTr: ' Marmara, Ege ve Akdeniz Sera tarımı kesimleri',
    regionsEn: 'Suburban green areas and micro-greenhouses nationwide',
    factTr: 'Eski Romalılar marulu akşam yemeklerinin sonunda uykuyu kolaylaştırması için yerlerdi (sütünde laktukaryum yatıştırıcısı vardır).',
    factEn: 'Ancient Romans consumed lettuce at dinner tables to prompt restful sleep due to its sedative latex.'
  },
  {
    id: 'salatalik',
    nameTr: 'Salatalık',
    nameEn: 'Cucumber',
    icon: '🥒',
    descTr: 'Kabakgillerden, sülüklerle sarılarak tırmanan, gevrek ve yüksek oranda su içeren popüler bir tek yıllık otsudur.',
    descEn: 'A creeping vine of the gourd family, climbing trellis nets and yielding crisp, hydrating green fruits.',
    healthTr: 'Vücuttan toksin atıcıdır; cildi serinletir, göz şişliklerini dindirir ve harika nem kazandırır.',
    healthEn: 'Naturally flushes internal toxins, cools localized skin cells, and serves as amazing rehydrator.',
    ecoTr: 'Geniş tırmanıcı gövdesiyle çıplak çitleri yapraklarıyla yeşil birer oksijen duvarına dönüştürür.',
    ecoEn: 'Quickly converts open vertical mesh trellises into active green corridors for city insects.',
    lifespanTr: '1 Yıl',
    lifespanEn: '1 Year',
    waterNeedTr: 'Yüksek (Günde periyodik can suyu ister; susuz kalırsa meyveleri aşırı derecede acılaşır)',
    waterNeedEn: 'High (Enjoys damp root environments; high summer dryness creates puckered, bitter harvests)',
    regionsTr: 'Ege ve Akdeniz Seracılığı ile tüm açık bahçeler',
    regionsEn: 'Cultivated in warm valleys and intensive coastal greenhouses of Turkey',
    factTr: 'Salatalık botanik olarak çekirdek barındırdığı için bir sebze değil, kavun-karpuz ile yakın akbaba olan bir meyvedir.',
    factEn: 'Because it carries seeds inside its flesh, cucumber is botanically defined as a fruit, not a vegetable.'
  },
  {
    id: 'domates',
    nameTr: 'Domates',
    nameEn: 'Tomato',
    icon: '🍅',
    descTr: 'Sarı çiçekli, tüylü kokulu yapraklı, kırmızı sulu çekirdekli meyveleriyle her mutfakta parlayan lider sebzedir.',
    descEn: 'An annual nightshade plant yielding red, plump, seed-filled fleshy sweet acid-balanced fruits.',
    healthTr: 'En zengin likopen deposudur; kalp krizi riskini önler ve cildi güneş ultraviyolesine karşı korur.',
    healthEn: 'Stuffed with anti-cancer lycopene; reduces high blood pressure and guards skin against UV damage.',
    ecoTr: 'Aromatik sülfat kokulu yaprakları sayesinde saksı yakınlarındaki haşereleri doğal olarak engeller.',
    ecoEn: 'Its pungent foliage essential oils discourage several species of insect pests from nesting.',
    lifespanTr: '1 Yıl',
    lifespanEn: '1 Year',
    waterNeedTr: 'Orta-Yüksek (Meyve verene kadar düzenli dipten sulanmalı; yapraklarını ıslatmamak gerekir)',
    waterNeedEn: 'Medium-High (Demands base soil irrigation; overhead sprays trigger early leaf blights)',
    regionsTr: 'Akdeniz (Antalya kıyı seracılığı) ve Ege (Çanakkale)',
    regionsEn: 'Antalya winter greenhouses and Çanakkale open summer crop fields',
    factTr: 'Domates, Avrupa\'ya ilk getirildiğinde zehirli sanıldığı için uzun süre sadece süs çiçeği olarak saksıda yetiştirilmiştir.',
    factEn: 'Upon first entering Europe, tomatoes were feared to be deadly and grown exclusively as ornamental house pots.'
  },
  {
    id: 'biber',
    nameTr: 'Biber',
    nameEn: 'Pepper',
    icon: '🫑',
    descTr: 'Patentli kapsaisin içeren, tatlıdan acıya geniş bir lezzet yelpazesi sunan şifalı tek yıllık sebzedir.',
    descEn: 'An annual nightshade crop yielding hollow seed-rich green, red, or yellow sweet or hot spicy pods.',
    healthTr: 'Metabolizmayı hızlandırır; acı türlerindeki kapsaisin ağrı kesicidir ve yağ yakımını hızlandırır.',
    healthEn: 'Speeds thermogenesis, and its capsaicin compound works as powerful analgesic and calorie burner.',
    ecoTr: 'Tüylü yapısıyla mikro bahçelerde tozlaşmayı canlı tutar, havalandırma yapar.',
    ecoEn: 'Supports micro-climatological air flow in organic garden rows through rapid canopy growth.',
    lifespanTr: '1 Yıl (Tropikal bölgelerde çok yıllık çalı gibi davranabilir)',
    lifespanEn: '1 Year (Can act as compact short-lived perennial shrub in warm tropical centers)',
    waterNeedTr: 'Orta (Çiçekteyken fazla sulanırsa çiçek döker, sarkan meyvede nizam can suyu ister)',
    waterNeedEn: 'Medium (Avoid waterlogging when blooming to prevent bud drop; needs steady base watering afterwards)',
    regionsTr: 'Akdeniz, Ege ve Doğu Akdeniz (Maraş, Urfa)',
    regionsEn: 'Aegean, Antalya coastal valleys, and Kahramanmaraş/Urfa plains',
    factTr: 'Acı biberdeki acılık hissi dilimizi fiziksel yakmaz; acı kapsaisin molekülü dildeki sıcaklık reseptörlerini uyarır.',
    factEn: 'Spicy pepper does not chemically burn tissues; capsaicin tricks brain thermal receptors into feeling heat.'
  },

  // --- ÖZEL BİTKİLER ---
  {
    id: 'kaktus',
    nameTr: 'Kaktüs',
    nameEn: 'Cactus',
    icon: '🌵',
    descTr: 'Dikenleriyle kendini çöl canavarlarından koruyan, gövdesinde tonlarca su depolayan efsanevi kuraklık şampiyonudur.',
    descEn: 'A magnificent succulent xerophytic genus with protective spines, adapted to survive parched soils.',
    healthTr: 'Odada elektromanyetik dalgaları azalttığı düşünülür; geceleri ortama saf taze oksijen yayar.',
    healthEn: 'Filters atmospheric fine dusts and releases clean oxygen during nighttime hours.',
    ecoTr: 'Zorlu kuru topraklarda çöl biyoçeşitliliği ve minik kuşlar için sarsılmaz bir su vahası görevi görür.',
    ecoEn: 'Acts as life-saving hydration oasis for wild desert birds and local crawling fauna.',
    lifespanTr: '10 - 200 Yıl',
    lifespanEn: '10 - 200 Years',
    waterNeedTr: 'Çok Düşük (Kışın neredeyse sıfır sulama ister; süzük kumlu kum çeper sever)',
    waterNeedEn: 'Very Low (Demands near-zero hydration in winter and sandy fast-drying potting soil mix)',
    regionsTr: 'Ege ve Akdeniz sahil mikro havzaları ile ev içi aydınlık saksıları',
    regionsEn: 'Hot southern shores and bright indoor desks nationwide',
    factTr: 'Dev Saguaro kaktüsünün kollarını çıkarması 75 yıl sürebilir ve gövdesinde 5 ton su saklayabilir.',
    factEn: 'A giant Saguaro cactus can store 5 metric tons of water inside, taking up to 75 years to grow its first arm.'
  },
  {
    id: 'bonsai',
    nameTr: 'Bonsai',
    nameEn: 'Bonsai',
    icon: '🌱',
    descTr: 'Geleneksel Japon saksı ve budama sanatıyla minyatür tutulan, asil duruşlu bilge canlı heykellerdir.',
    descEn: 'The exquisite Japanese art of training dwarfed gnarled woody trees in shallow ceramic pots representing balance.',
    healthTr: 'Zihni derinlemesine sakinleştirir; budama ve yaprak bakımı sabrı ve terapik mutluluğu parlatır.',
    healthEn: 'Nurturing and precise styling induces zen-like focus, serving as amazing active therapeutic hobby.',
    ecoTr: 'Dar kök sınırında yüksek verimli oksijen üretir; odanın bağıl nem dengesini dengeler.',
    ecoEn: 'Supplies high-efficiency indoor micro-oxygen nodes and balances localized humidity patterns.',
    lifespanTr: '50 - 500 Yıl (Usta bahçıvanlar elinde nesilden nesile aktarılarak yaşatılır)',
    lifespanEn: '50 - 500 Years (Can live for centuries if inherited and trimmed by consecutive generations)',
    waterNeedTr: 'Orta (Sarı saksısı küçük olduğunda kurumaması için periyodik fısfıs nem ister)',
    waterNeedEn: 'Medium (Tiny shallow containers demand steady micro-spraying and checking organic soil dampness)',
    regionsTr: 'Tüm Türkiye genelinde iç mekanda ve cam saksılarda',
    regionsEn: 'Grown indoors as highly prized green art pieces across all provinces',
    factTr: 'Bonsai tek bir ağaç familyası değildir; çam, meşe, servi gibi her türlü ağaç bonsai metoduyla minyatürleştirilebilir.',
    factEn: 'Bonsai is a trimming discipline rather than a species; almost any woody deciduous or evergreen tree can be used.'
  },
  {
    id: 'bambu',
    nameTr: 'Bambu',
    nameEn: 'Bamboo',
    icon: '🎋',
    descTr: 'İçi boş dayanıklı boğumlara sahip gövdesi olan, inanılmaz hızlı büyüyen çok asil bir tropik buğdaygildir.',
    descEn: 'A giant arborescent woody grass genus with hollow internodes, famous for record-breaking growth speeds.',
    healthTr: 'Antioksidan mineral deposudur, yapraklarındaki silika tırnak ve saç hücrelerini canlandırır.',
    healthEn: 'Saturated with natural botanical silica; strengthens nails, locks hair fibers, and acts as trace mineral rejuvenator.',
    ecoTr: 'Standart bir ağaca göre %35 daha fazla oksijen üretir ve büyük karbon emisyon süzme kılıcıdır.',
    ecoEn: 'Produces 35% more oxygen than equivalent woody trees, functioning as elite atmospheric filter.',
    lifespanTr: '20 - 100 Yıl',
    lifespanEn: '20 - 100 Years',
    waterNeedTr: 'Yüksek (Suda dahi köklenebilir; sürekli nemli, humuslu balçık zemin diler)',
    waterNeedEn: 'High (Thrives in water tables or constant wet, humic clay substrates with rich nutrients)',
    regionsTr: 'Karadeniz\'in en ılık vadileri ile ev dekorasyon saksıları',
    regionsEn: 'Warm regions of East Black Sea and indoor water-vials nationwide',
    factTr: 'Bazı dev bambu türleri, günde 91 santimetreye kadar uzayarak dünyadaki en hızlı büyüyen bitki unvanının sahibidir.',
    factEn: 'Certain giant bamboo species can shoot up to 91 cm in 24 hours, making it the fastest-growing plant on Earth.'
  },
  {
    id: 'yonca',
    nameTr: 'Yonca',
    nameEn: 'Clover',
    icon: '🍀',
    descTr: 'Üç yapraklı narin meralık otsu, kökleriyle toprağa can katan yeşil bir şans ve bereket çiçeğidir.',
    descEn: 'A delicate low-growing perennial herbaceous legume root-enriching ground cover representing good luck.',
    healthTr: 'Katıksız klorofil, kalsiyum ve fitoöstrojen deposudur; kanı temizler halsizliği bitirir.',
    healthEn: 'Stuffed with raw clean chlorophyll, calcium, and phytoestrogens; purifies vascular chains and combats anemia.',
    ecoTr: 'Kökündeki rhizobium bakterileriyle toprağa azot bağlayarak suni kimyasal gübre ihtiyacını bitirir.',
    ecoEn: 'Acts as highly efficient nitrogen-fixer via root bacteria, upgrading poor soils naturally.',
    lifespanTr: '3 - 8 Yıl',
    lifespanEn: '3 - 8 Years',
    waterNeedTr: 'Orta (Serin mevsimlerde can suyu almayı, kışın ise don altında kalmayı sever)',
    waterNeedEn: 'Medium (Prefers regular moderate rain showers and cooler spring soil temperatures)',
    regionsTr: 'Tüm Türkiye ova, tarla ve meralarında',
    regionsEn: 'Thrives in wild open pastures, fields, and village meadows nationwide',
    factTr: 'Doğada rastlanması 10.000\'de 1 olasılık olan dört yapraklı yonca, antik kabilelerden beri şans sembolüdür.',
    factEn: 'Finding a rare four-leaf clover has a 1 in 10,000 statistical probability, celebrated as card of fortune.'
  }
];

export const THIRTY_PLANTS = FIFTY_PLANTS;
