export interface DamDetail {
  id: string;
  cityName: string;
  cityNameEn: string;
  damName: string;
  damNameEn: string;
  fullness: number; // %
  weeklyChange: number; // %
  monthlyChange: number; // %
  yearlyChange: number; // %
  riskLevel: 'critical' | 'warning' | 'safe';
  droughtLabelTr: string;
  droughtLabelEn: string;
  usableWater: number; // Million m³
  lastUpdate: string;
}

// 81 Provinces of Turkey in alphabetical / plate order
const RAW_TURKEY_PROVINCES_DAMS: DamDetail[] = [
  {
    id: '01',
    cityName: 'Adana',
    cityNameEn: 'Adana',
    damName: 'Seyhan Barajı',
    damNameEn: 'Seyhan Dam',
    fullness: 58,
    weeklyChange: 1.2,
    monthlyChange: 5.4,
    yearlyChange: -2.3,
    riskLevel: 'safe',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 720.5,
    lastUpdate: 'Canlı • 10 dakika önce güncellendi'
  },
  {
    id: '02',
    cityName: 'Adıyaman',
    cityNameEn: 'Adiyaman',
    damName: 'Atatürk Barajı',
    damNameEn: 'Ataturk Dam',
    fullness: 62,
    weeklyChange: 0.8,
    monthlyChange: 4.1,
    yearlyChange: 8.5,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Nemli',
    droughtLabelEn: 'Normal Humid',
    usableWater: 48700,
    lastUpdate: 'Canlı • 15 dakika önce güncellendi'
  },
  {
    id: '03',
    cityName: 'Afyonkarahisar',
    cityNameEn: 'Afyonkarahisar',
    damName: 'Selevir Barajı',
    damNameEn: 'Selevir Dam',
    fullness: 34,
    weeklyChange: -0.4,
    monthlyChange: -2.1,
    yearlyChange: -6.4,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 32.8,
    lastUpdate: 'Canlı • 34 dakika önce güncellendi'
  },
  {
    id: '04',
    cityName: 'Ağrı',
    cityNameEn: 'Agri',
    damName: 'Yazıcı Barajı',
    damNameEn: 'Yazici Dam',
    fullness: 48,
    weeklyChange: -0.1,
    monthlyChange: 1.5,
    yearlyChange: -1.2,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 92.4,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '05',
    cityName: 'Amasya',
    cityNameEn: 'Amasya',
    damName: 'Yedikır Barajı',
    damNameEn: 'Yedikir Dam',
    fullness: 39,
    weeklyChange: -0.5,
    monthlyChange: -1.8,
    yearlyChange: -3.5,
    riskLevel: 'warning',
    droughtLabelTr: 'Ciddi Kuraklık Riski',
    droughtLabelEn: 'Severe Drought Risk',
    usableWater: 24.1,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '06',
    cityName: 'Ankara',
    cityNameEn: 'Ankara',
    damName: 'Çamlıdere Barajı',
    damNameEn: 'Camlidere Dam',
    fullness: 41,
    weeklyChange: 0.3,
    monthlyChange: -1.2,
    yearlyChange: -5.1,
    riskLevel: 'warning',
    droughtLabelTr: 'Ciddi Kuraklık Alarmı',
    droughtLabelEn: 'Severe Drought Warning',
    usableWater: 442.0,
    lastUpdate: 'Canlı • 5 dakika önce güncellendi'
  },
  {
    id: '07',
    cityName: 'Antalya',
    cityNameEn: 'Antalya',
    damName: 'Oymapınar Barajı',
    damNameEn: 'Oymapinar Dam',
    fullness: 74,
    weeklyChange: 2.1,
    monthlyChange: 8.6,
    yearlyChange: 12.4,
    riskLevel: 'safe',
    droughtLabelTr: 'Çok Nemli',
    droughtLabelEn: 'Very Humid',
    usableWater: 220.5,
    lastUpdate: 'Canlı • 23 dakika önce güncellendi'
  },
  {
    id: '08',
    cityName: 'Artvin',
    cityNameEn: 'Artvin',
    damName: 'Deriner Barajı',
    damNameEn: 'Deriner Dam',
    fullness: 82,
    weeklyChange: 1.5,
    monthlyChange: 7.2,
    yearlyChange: 14.8,
    riskLevel: 'safe',
    droughtLabelTr: 'Aşırı Nemli',
    droughtLabelEn: 'Extremely Humid',
    usableWater: 1540.2,
    lastUpdate: 'Canlı • 45 dakika önce güncellendi'
  },
  {
    id: '09',
    cityName: 'Aydın',
    cityNameEn: 'Aydin',
    damName: 'Kemer Barajı',
    damNameEn: 'Kemer Dam',
    fullness: 26,
    weeklyChange: -1.4,
    monthlyChange: -4.5,
    yearlyChange: -11.2,
    riskLevel: 'critical',
    droughtLabelTr: 'Olağanüstü Kuraklık',
    droughtLabelEn: 'Extreme Drought Warning',
    usableWater: 94.6,
    lastUpdate: 'Canlı • 12 dakika önce güncellendi'
  },
  {
    id: '10',
    cityName: 'Balıkesir',
    cityNameEn: 'Balikesir',
    damName: 'İkizcetepeler Barajı',
    damNameEn: 'Ikizcetepeler Dam',
    fullness: 35,
    weeklyChange: -0.8,
    monthlyChange: -2.4,
    yearlyChange: -8.1,
    riskLevel: 'warning',
    droughtLabelTr: 'Şiddetli Kuraklık',
    droughtLabelEn: 'Severe Drought Warning',
    usableWater: 54.3,
    lastUpdate: 'Canlı • 32 dakika önce güncellendi'
  },
  {
    id: '11',
    cityName: 'Bilecik',
    cityNameEn: 'Bilecik',
    damName: 'Kızıldamlar Barajı',
    damNameEn: 'Kizildamlar Dam',
    fullness: 43,
    weeklyChange: -0.3,
    monthlyChange: -0.9,
    yearlyChange: -4.2,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 18.7,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '12',
    cityName: 'Bingöl',
    cityNameEn: 'Bingol',
    damName: 'Özlüce Barajı',
    damNameEn: 'Ozluce Dam',
    fullness: 68,
    weeklyChange: 1.1,
    monthlyChange: 3.5,
    yearlyChange: 9.2,
    riskLevel: 'safe',
    droughtLabelTr: 'Nemli',
    droughtLabelEn: 'Humid',
    usableWater: 820.6,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '13',
    cityName: 'Bitlis',
    cityNameEn: 'Bitlis',
    damName: 'Arpaşan Regülatörü',
    damNameEn: 'Arpasan Regulator',
    fullness: 70,
    weeklyChange: 0.9,
    monthlyChange: 2.8,
    yearlyChange: 11.5,
    riskLevel: 'safe',
    droughtLabelTr: 'Nemli',
    droughtLabelEn: 'Humid',
    usableWater: 45.0,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '14',
    cityName: 'Bolu',
    cityNameEn: 'Bolu',
    damName: 'Gölköy Barajı',
    damNameEn: 'Golkoy Dam',
    fullness: 52,
    weeklyChange: -0.2,
    monthlyChange: -1.1,
    yearlyChange: -3.4,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 12.4,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '15',
    cityName: 'Burdur',
    cityNameEn: 'Burdur',
    damName: 'Karacaören II Barajı',
    damNameEn: 'Karacaoren II Dam',
    fullness: 29,
    weeklyChange: -1.1,
    monthlyChange: -3.8,
    yearlyChange: -9.5,
    riskLevel: 'critical',
    droughtLabelTr: 'Şiddetli Kuraklık',
    droughtLabelEn: 'Severe Drought Warning',
    usableWater: 8.6,
    lastUpdate: 'Canlı • 42 dakika önce güncellendi'
  },
  {
    id: '16',
    cityName: 'Bursa',
    cityNameEn: 'Bursa',
    damName: 'Doğancı Barajı',
    damNameEn: 'Doganci Dam',
    fullness: 54,
    weeklyChange: -0.5,
    monthlyChange: 2.3,
    yearlyChange: -1.8,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 65.4,
    lastUpdate: 'Canlı • 14 dakika önce güncellendi'
  },
  {
    id: '17',
    cityName: 'Çankırı',
    cityNameEn: 'Cankiri',
    damName: 'Güldürcek Barajı',
    damNameEn: 'Guldurcek Dam',
    fullness: 32,
    weeklyChange: -0.6,
    monthlyChange: -2.3,
    yearlyChange: -6.1,
    riskLevel: 'warning',
    droughtLabelTr: 'Şiddetli Kuraklık',
    droughtLabelEn: 'Severe Drought',
    usableWater: 16.5,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '18',
    cityName: 'Çorum',
    cityNameEn: 'Corum',
    damName: 'Yenihayat Barajı',
    damNameEn: 'Yenihayat Dam',
    fullness: 45,
    weeklyChange: -0.1,
    monthlyChange: 1.0,
    yearlyChange: -2.4,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 11.2,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '19',
    cityName: 'Denizli',
    cityNameEn: 'Denizli',
    damName: 'Gökpınar Barajı',
    damNameEn: 'Gokpinar Dam',
    fullness: 38,
    weeklyChange: -0.9,
    monthlyChange: -3.1,
    yearlyChange: -7.5,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 43.1,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '20',
    cityName: 'Diyarbakır',
    cityNameEn: 'Diyarbakir',
    damName: 'Karakaya Barajı',
    damNameEn: 'Karakaya Dam',
    fullness: 65,
    weeklyChange: 1.0,
    monthlyChange: 4.8,
    yearlyChange: 7.9,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Nemli',
    droughtLabelEn: 'Normal Humid',
    usableWater: 5200,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '21',
    cityName: 'Edirne',
    cityNameEn: 'Edirne',
    damName: 'Süloğlu Barajı',
    damNameEn: 'Suloglu Dam',
    fullness: 47,
    weeklyChange: -0.4,
    monthlyChange: -1.7,
    yearlyChange: -4.3,
    riskLevel: 'warning',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 21.0,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '22',
    cityName: 'Elazığ',
    cityNameEn: 'Elazig',
    damName: 'Keban Barajı',
    damNameEn: 'Keban Dam',
    fullness: 71,
    weeklyChange: 1.4,
    monthlyChange: 5.2,
    yearlyChange: 10.3,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Nemli',
    droughtLabelEn: 'Normal Humid',
    usableWater: 24300,
    lastUpdate: 'Canlı • 25 dakika önce güncellendi'
  },
  {
    id: '23',
    cityName: 'Erzincan',
    cityNameEn: 'Erzincan',
    damName: 'Tercan Barajı',
    damNameEn: 'Tercan Dam',
    fullness: 54,
    weeklyChange: -0.1,
    monthlyChange: 2.1,
    yearlyChange: 4.5,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 110.4,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '24',
    cityName: 'Erzurum',
    cityNameEn: 'Erzurum',
    damName: 'Dumlu Barajı',
    damNameEn: 'Dumlu Dam',
    fullness: 59,
    weeklyChange: 0.5,
    monthlyChange: 3.4,
    yearlyChange: 5.8,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 182.5,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '25',
    cityName: 'Eskişehir',
    cityNameEn: 'Eskisehir',
    damName: 'Porsuk Barajı',
    damNameEn: 'Porsuk Dam',
    fullness: 36,
    weeklyChange: -0.7,
    monthlyChange: -2.8,
    yearlyChange: -6.9,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 154.2,
    lastUpdate: 'Canlı • 18 dakika önce güncellendi'
  },
  {
    id: '26',
    cityName: 'Gaziantep',
    cityNameEn: 'Gaziantep',
    damName: 'Hacıbaba Barajı',
    damNameEn: 'Hacibaba Dam',
    fullness: 42,
    weeklyChange: -0.3,
    monthlyChange: 1.1,
    yearlyChange: -3.8,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 41.5,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '27',
    cityName: 'Giresun',
    cityNameEn: 'Giresun',
    damName: 'Kılıçkaya Barajı',
    damNameEn: 'Kilickaya Dam',
    fullness: 76,
    weeklyChange: 1.8,
    monthlyChange: 6.9,
    yearlyChange: 11.2,
    riskLevel: 'safe',
    droughtLabelTr: 'Çok Nemli',
    droughtLabelEn: 'Very Humid',
    usableWater: 430.7,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '28',
    cityName: 'Gümüşhane',
    cityNameEn: 'Gumushane',
    damName: 'Kürtün Barajı',
    damNameEn: 'Kurtun Dam',
    fullness: 72,
    weeklyChange: 1.1,
    monthlyChange: 5.3,
    yearlyChange: 8.4,
    riskLevel: 'safe',
    droughtLabelTr: 'Nemli',
    droughtLabelEn: 'Humid',
    usableWater: 38.6,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '29',
    cityName: 'Hakkari',
    cityNameEn: 'Hakkari',
    damName: 'Zap Nehri Havzası',
    damNameEn: 'Zap River Basin',
    fullness: 65,
    weeklyChange: 0.4,
    monthlyChange: 1.8,
    yearlyChange: 6.5,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 520,
    lastUpdate: 'Canlı • 5 saat önce güncellendi'
  },
  {
    id: '30',
    cityName: 'Hatay',
    cityNameEn: 'Hatay',
    damName: 'Yarseli Barajı',
    damNameEn: 'Yarseli Dam',
    fullness: 30,
    weeklyChange: -1.2,
    monthlyChange: -4.1,
    yearlyChange: -9.2,
    riskLevel: 'critical',
    droughtLabelTr: 'Olağanüstü Kuraklık',
    droughtLabelEn: 'Extreme Drought Warning',
    usableWater: 24.8,
    lastUpdate: 'Canlı • 21 dakika önce güncellendi'
  },
  {
    id: '31',
    cityName: 'Isparta',
    cityNameEn: 'Isparta',
    damName: 'Eğirdir Gölü Kaynağı',
    damNameEn: 'Egirdir Lake Source',
    fullness: 33,
    weeklyChange: -1.0,
    monthlyChange: -3.5,
    yearlyChange: -8.8,
    riskLevel: 'critical',
    droughtLabelTr: 'Şiddetli Kuraklık',
    droughtLabelEn: 'Severe Drought Warning',
    usableWater: 340.5,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '32',
    cityName: 'Mersin',
    cityNameEn: 'Mersin',
    damName: 'Gezende Barajı',
    damNameEn: 'Gezende Dam',
    fullness: 51,
    weeklyChange: -0.2,
    monthlyChange: 2.1,
    yearlyChange: -4.1,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 28.6,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '33',
    cityName: 'İstanbul',
    cityNameEn: 'Istanbul',
    damName: 'Ömerli Barajı',
    damNameEn: 'Omerli Dam',
    fullness: 28,
    weeklyChange: -1.2,
    monthlyChange: -3.8,
    yearlyChange: -9.5,
    riskLevel: 'critical',
    droughtLabelTr: 'Olağanüstü Kuraklık',
    droughtLabelEn: 'Extreme Drought Warning',
    usableWater: 235.4,
    lastUpdate: 'Canlı • Şimdi güncellendi'
  },
  {
    id: '34',
    cityName: 'İzmir',
    cityNameEn: 'Izmir',
    damName: 'Tahtalı Barajı',
    damNameEn: 'Tahtali Dam',
    fullness: 31,
    weeklyChange: -0.9,
    monthlyChange: -3.0,
    yearlyChange: -7.2,
    riskLevel: 'critical',
    droughtLabelTr: 'Olağanüstü Kuraklık',
    droughtLabelEn: 'Extreme Drought Warning',
    usableWater: 94.8,
    lastUpdate: 'Canlı • Şimdi güncellendi'
  },
  {
    id: '35',
    cityName: 'Kars',
    cityNameEn: 'Kars',
    damName: 'Arpaçay Barajı',
    damNameEn: 'Arpacay Dam',
    fullness: 48,
    weeklyChange: -0.2,
    monthlyChange: 1.1,
    yearlyChange: -1.5,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 430.3,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '36',
    cityName: 'Kastamonu',
    cityNameEn: 'Kastamonu',
    damName: 'Karaçomak Barajı',
    damNameEn: 'Karacomak Dam',
    fullness: 44,
    weeklyChange: -0.5,
    monthlyChange: -1.9,
    yearlyChange: -4.1,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 11.4,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '37',
    cityName: 'Kayseri',
    cityNameEn: 'Kayseri',
    damName: 'Yamula Barajı',
    damNameEn: 'Yamula Dam',
    fullness: 53,
    weeklyChange: 0.1,
    monthlyChange: 2.8,
    yearlyChange: -1.2,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 1840.5,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '38',
    cityName: 'Kırklareli',
    cityNameEn: 'Kirklareli',
    damName: 'Kayalık Barajı',
    damNameEn: 'Kayalik Dam',
    fullness: 39,
    weeklyChange: -0.8,
    monthlyChange: -2.3,
    yearlyChange: -5.4,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 45.1,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '39',
    cityName: 'Kırşehir',
    cityNameEn: 'Kirsehir',
    damName: 'Sarımsaklı Barajı',
    damNameEn: 'Sarimsakli Dam',
    fullness: 35,
    weeklyChange: -0.6,
    monthlyChange: -2.1,
    yearlyChange: -4.8,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 9.8,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '40',
    cityName: 'Kocaeli',
    cityNameEn: 'Kocaeli',
    damName: 'Yuvacık Barajı',
    damNameEn: 'Yuvacik Dam',
    fullness: 64,
    weeklyChange: -0.3,
    monthlyChange: -1.2,
    yearlyChange: 3.2,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 32.7,
    lastUpdate: 'Canlı • 12 dakika önce güncellendi'
  },
  {
    id: '41',
    cityName: 'Konya',
    cityNameEn: 'Konya',
    damName: 'Altınapa Barajı',
    damNameEn: 'Altinapa Dam',
    fullness: 19,
    weeklyChange: -1.8,
    monthlyChange: -5.4,
    yearlyChange: -12.4,
    riskLevel: 'critical',
    droughtLabelTr: 'Olağanüstü Kuraklık',
    droughtLabelEn: 'Extreme Drought Warning',
    usableWater: 6.2,
    lastUpdate: 'Canlı • 4 dakika önce güncellendi'
  },
  {
    id: '42',
    cityName: 'Kütahya',
    cityNameEn: 'Kutahya',
    damName: 'Enne Barajı',
    damNameEn: 'Enne Dam',
    fullness: 48,
    weeklyChange: -0.3,
    monthlyChange: -1.1,
    yearlyChange: -4.0,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 18.6,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '43',
    cityName: 'Malatya',
    cityNameEn: 'Malatya',
    damName: 'Çat Barajı',
    damNameEn: 'Cat Dam',
    fullness: 51,
    weeklyChange: 0.1,
    monthlyChange: 1.8,
    yearlyChange: -2.3,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 142.3,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '44',
    cityName: 'Manisa',
    cityNameEn: 'Manisa',
    damName: 'Demirköprü Barajı',
    damNameEn: 'Demirkopru Dam',
    fullness: 24,
    weeklyChange: -1.2,
    monthlyChange: -3.9,
    yearlyChange: -10.4,
    riskLevel: 'critical',
    droughtLabelTr: 'Olağanüstü Kuraklık',
    droughtLabelEn: 'Extreme Drought Warning',
    usableWater: 104.5,
    lastUpdate: 'Canlı • 42 dakika önce güncellendi'
  },
  {
    id: '45',
    cityName: 'Kahramanmaraş',
    cityNameEn: 'Kahramanmaras',
    damName: 'Menzelet Barajı',
    damNameEn: 'Menzelet Dam',
    fullness: 63,
    weeklyChange: 0.5,
    monthlyChange: 3.1,
    yearlyChange: 8.1,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Nemli',
    droughtLabelEn: 'Normal Humid',
    usableWater: 1120,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '46',
    cityName: 'Mardin',
    cityNameEn: 'Mardin',
    damName: 'Ilısu Dam Kaynağı',
    damNameEn: 'Ilisu Dam Basin',
    fullness: 58,
    weeklyChange: 0.4,
    monthlyChange: 2.0,
    yearlyChange: 6.9,
    riskLevel: 'safe',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 3200,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '47',
    cityName: 'Muğla',
    cityNameEn: 'Mugla',
    damName: 'Geyik Barajı',
    damNameEn: 'Geyik Dam',
    fullness: 30,
    weeklyChange: -1.5,
    monthlyChange: -4.8,
    yearlyChange: -12.1,
    riskLevel: 'critical',
    droughtLabelTr: 'Olağanüstü Kuraklık',
    droughtLabelEn: 'Extreme Drought Warning',
    usableWater: 12.8,
    lastUpdate: 'Canlı • 15 dakika önce güncellendi'
  },
  {
    id: '48',
    cityName: 'Muş',
    cityNameEn: 'Mus',
    damName: 'Alparslan-1 Barajı',
    damNameEn: 'Alparslan-1 Dam',
    fullness: 72,
    weeklyChange: 1.2,
    monthlyChange: 4.5,
    yearlyChange: 9.8,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Nemli',
    droughtLabelEn: 'Normal Humid',
    usableWater: 1420,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '49',
    cityName: 'Nevşehir',
    cityNameEn: 'Nevsehir',
    damName: 'Kızılırmak Yatak Havzası',
    damNameEn: 'Kizilirmak River Bed',
    fullness: 44,
    weeklyChange: -0.4,
    monthlyChange: -1.2,
    yearlyChange: -3.8,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 89.0,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '50',
    cityName: 'Niğde',
    cityNameEn: 'Nigde',
    damName: 'Gümüşler Barajı',
    damNameEn: 'Gumusler Dam',
    fullness: 40,
    weeklyChange: -0.5,
    monthlyChange: -1.8,
    yearlyChange: -4.2,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 5.6,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '51',
    cityName: 'Ordu',
    cityNameEn: 'Ordu',
    damName: 'Topçam Barajı',
    damNameEn: 'Topcam Dam',
    fullness: 78,
    weeklyChange: 2.0,
    monthlyChange: 6.8,
    yearlyChange: 12.5,
    riskLevel: 'safe',
    droughtLabelTr: 'Çok Nemli',
    droughtLabelEn: 'Very Humid',
    usableWater: 72.8,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '52',
    cityName: 'Rize',
    cityNameEn: 'Rize',
    damName: 'Andon Su Alma Tesisi',
    damNameEn: 'Andon Water Intake',
    fullness: 88,
    weeklyChange: 2.5,
    monthlyChange: 9.2,
    yearlyChange: 16.5,
    riskLevel: 'safe',
    droughtLabelTr: 'Aşırı Nemli',
    droughtLabelEn: 'Extremely Humid',
    usableWater: 18.2,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '53',
    cityName: 'Sakarya',
    cityNameEn: 'Sakarya',
    damName: 'Sapanca Gölü',
    damNameEn: 'Sapanca Lake',
    fullness: 68,
    weeklyChange: -0.2,
    monthlyChange: -1.1,
    yearlyChange: 4.1,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 380,
    lastUpdate: 'Canlı • 12 dakika önce güncellendi'
  },
  {
    id: '54',
    cityName: 'Samsun',
    cityNameEn: 'Samsun',
    damName: 'Altınkaya Barajı',
    damNameEn: 'Altinkaya Dam',
    fullness: 56,
    weeklyChange: -0.4,
    monthlyChange: 1.5,
    yearlyChange: -2.3,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 3450,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '55',
    cityName: 'Siirt',
    cityNameEn: 'Siirt',
    damName: 'Alkumru Barajı',
    damNameEn: 'Alkumru Dam',
    fullness: 64,
    weeklyChange: 0.8,
    monthlyChange: 3.2,
    yearlyChange: 7.4,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 310.5,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '56',
    cityName: 'Sinop',
    cityNameEn: 'Sinop',
    damName: 'Erfelek Barajı',
    damNameEn: 'Erfelek Dam',
    fullness: 72,
    weeklyChange: 1.1,
    monthlyChange: 4.5,
    yearlyChange: 9.8,
    riskLevel: 'safe',
    droughtLabelTr: 'Nemli',
    droughtLabelEn: 'Humid',
    usableWater: 24.6,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '57',
    cityName: 'Sivas',
    cityNameEn: 'Sivas',
    damName: 'Pusat-Özen Barajı',
    damNameEn: 'Pusat-Ozen Dam',
    fullness: 31,
    weeklyChange: -0.9,
    monthlyChange: -3.1,
    yearlyChange: -6.8,
    riskLevel: 'critical',
    droughtLabelTr: 'Şiddetli Kuraklık',
    droughtLabelEn: 'Severe Drought Warning',
    usableWater: 29.5,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '58',
    cityName: 'Tekirdağ',
    cityNameEn: 'Tekirdag',
    damName: 'Naip Barajı',
    damNameEn: 'Naip Dam',
    fullness: 39,
    weeklyChange: -0.7,
    monthlyChange: -2.0,
    yearlyChange: -4.5,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 12.3,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '59',
    cityName: 'Tokat',
    cityNameEn: 'Tokat',
    damName: 'Almus Barajı',
    damNameEn: 'Almus Dam',
    fullness: 51,
    weeklyChange: -0.2,
    monthlyChange: 1.4,
    yearlyChange: -1.9,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 480,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '60',
    cityName: 'Trabzon',
    cityNameEn: 'Trabzon',
    damName: 'Atasu Barajı',
    damNameEn: 'Atasu Dam',
    fullness: 82,
    weeklyChange: 2.1,
    monthlyChange: 7.4,
    yearlyChange: 11.8,
    riskLevel: 'safe',
    droughtLabelTr: 'Çok Nemli',
    droughtLabelEn: 'Very Humid',
    usableWater: 31.4,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '61',
    cityName: 'Tunceli',
    cityNameEn: 'Tunceli',
    damName: 'Uzunçayır Barajı',
    damNameEn: 'Uzuncayir Dam',
    fullness: 70,
    weeklyChange: 1.0,
    monthlyChange: 3.8,
    yearlyChange: 8.5,
    riskLevel: 'safe',
    droughtLabelTr: 'Nemli',
    droughtLabelEn: 'Humid',
    usableWater: 280.2,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '62',
    cityName: 'Şanlıurfa',
    cityNameEn: 'Sanliurfa',
    damName: 'Birecik Barajı',
    damNameEn: 'Birecik Dam',
    fullness: 60,
    weeklyChange: 0.6,
    monthlyChange: 2.8,
    yearlyChange: 4.1,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Nemli',
    droughtLabelEn: 'Normal Humid',
    usableWater: 890,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '63',
    cityName: 'Uşak',
    cityNameEn: 'Usak',
    damName: 'Küçükler Barajı',
    damNameEn: 'Kucukler Dam',
    fullness: 34,
    weeklyChange: -0.8,
    monthlyChange: -2.3,
    yearlyChange: -6.0,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 4.8,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '64',
    cityName: 'Van',
    cityNameEn: 'Van',
    damName: 'Sarımehmet Barajı',
    damNameEn: 'Sarimehmet Dam',
    fullness: 43,
    weeklyChange: -0.4,
    monthlyChange: -1.5,
    yearlyChange: -3.8,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 72.8,
    lastUpdate: 'Canlı • 5 saat önce güncellendi'
  },
  {
    id: '65',
    cityName: 'Yozgat',
    cityNameEn: 'Yozgat',
    damName: 'Gelingüllü Barajı',
    damNameEn: 'Gelingullu Dam',
    fullness: 39,
    weeklyChange: -0.5,
    monthlyChange: -1.9,
    yearlyChange: -4.1,
    riskLevel: 'warning',
    droughtLabelTr: 'Orta Kuraklık',
    droughtLabelEn: 'Moderate Drought',
    usableWater: 48.5,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '66',
    cityName: 'Zonguldak',
    cityNameEn: 'Zonguldak',
    damName: 'Ulutan Barajı',
    damNameEn: 'Ulutan Dam',
    fullness: 67,
    weeklyChange: -0.1,
    monthlyChange: -0.8,
    yearlyChange: 3.8,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 18.4,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '67',
    cityName: 'Aksaray',
    cityNameEn: 'Aksaray',
    damName: 'Mamasın Barajı',
    damNameEn: 'Mamasin Dam',
    fullness: 28,
    weeklyChange: -1.1,
    monthlyChange: -3.9,
    yearlyChange: -8.4,
    riskLevel: 'critical',
    droughtLabelTr: 'Şiddetli Kuraklık',
    droughtLabelEn: 'Severe Drought Warning',
    usableWater: 22.4,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '68',
    cityName: 'Bayburt',
    cityNameEn: 'Bayburt',
    damName: 'Demirözü Barajı',
    damNameEn: 'Demirozu Dam',
    fullness: 65,
    weeklyChange: 0.8,
    monthlyChange: 3.1,
    yearlyChange: 5.4,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 38.2,
    lastUpdate: 'Canlı • 3 saat önce güncellendi'
  },
  {
    id: '69',
    cityName: 'Karaman',
    cityNameEn: 'Karaman',
    damName: 'İbrala Barajı',
    damNameEn: 'Ibrala Dam',
    fullness: 27,
    weeklyChange: -1.3,
    monthlyChange: -4.5,
    yearlyChange: -9.8,
    riskLevel: 'critical',
    droughtLabelTr: 'Olağanüstü Kuraklık',
    droughtLabelEn: 'Extreme Drought Warning',
    usableWater: 14.5,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '70',
    cityName: 'Kırıkkale',
    cityNameEn: 'Kirikkale',
    damName: 'Kapulukaya Barajı',
    damNameEn: 'Kapulukaya Dam',
    fullness: 48,
    weeklyChange: -0.2,
    monthlyChange: -0.9,
    yearlyChange: -3.1,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 190.5,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '71',
    cityName: 'Batman',
    cityNameEn: 'Batman',
    damName: 'Batman Barajı',
    damNameEn: 'Batman Dam',
    fullness: 68,
    weeklyChange: 1.0,
    monthlyChange: 3.8,
    yearlyChange: 8.4,
    riskLevel: 'safe',
    droughtLabelTr: 'Nemli',
    droughtLabelEn: 'Humid',
    usableWater: 680,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '72',
    cityName: 'Şırnak',
    cityNameEn: 'Sirnak',
    damName: 'Dicle Nehri Yatağı',
    damNameEn: 'Tigris River Bed',
    fullness: 62,
    weeklyChange: 0.5,
    monthlyChange: 2.1,
    yearlyChange: 5.8,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 940,
    lastUpdate: 'Canlı • 5 saat önce güncellendi'
  },
  {
    id: '73',
    cityName: 'Bartın',
    cityNameEn: 'Bartin',
    damName: 'Kirazlıköprü Barajı',
    damNameEn: 'Kirazlikopru Dam',
    fullness: 72,
    weeklyChange: 1.2,
    monthlyChange: 4.8,
    yearlyChange: 10.4,
    riskLevel: 'safe',
    droughtLabelTr: 'Nemli',
    droughtLabelEn: 'Humid',
    usableWater: 42.1,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '74',
    cityName: 'Ardahan',
    cityNameEn: 'Ardahan',
    damName: 'Köroğlu Barajı',
    damNameEn: 'Koroglu Dam',
    fullness: 58,
    weeklyChange: -0.1,
    monthlyChange: 1.8,
    yearlyChange: 3.2,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 58.0,
    lastUpdate: 'Canlı • 4 saat önce güncellendi'
  },
  {
    id: '75',
    cityName: 'Iğdır',
    cityNameEn: 'Igdir',
    damName: 'Ünlendi Barajı',
    damNameEn: 'Unlendi Dam',
    fullness: 44,
    weeklyChange: -0.3,
    monthlyChange: -1.0,
    yearlyChange: -3.5,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 32.4,
    lastUpdate: 'Canlı • 5 saat önce güncellendi'
  },
  {
    id: '76',
    cityName: 'Yalova',
    cityNameEn: 'Yalova',
    damName: 'Gökçe Barajı',
    damNameEn: 'Gokce Dam',
    fullness: 61,
    weeklyChange: -0.5,
    monthlyChange: -1.8,
    yearlyChange: 2.1,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 14.8,
    lastUpdate: 'Canlı • 10 dakika önce güncellendi'
  },
  {
    id: '77',
    cityName: 'Karabük',
    cityNameEn: 'Karabuk',
    damName: 'Aldere Su Kaynağı',
    damNameEn: 'Aldere Water Source',
    fullness: 64,
    weeklyChange: -0.2,
    monthlyChange: -1.1,
    yearlyChange: 3.0,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 11.2,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '78',
    cityName: 'Kilis',
    cityNameEn: 'Kilis',
    damName: 'Seve Barajı',
    damNameEn: 'Seve Dam',
    fullness: 28,
    weeklyChange: -1.5,
    monthlyChange: -4.8,
    yearlyChange: -11.4,
    riskLevel: 'critical',
    droughtLabelTr: 'Şiddetli Kuraklık',
    droughtLabelEn: 'Severe Drought Warning',
    usableWater: 4.2,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '79',
    cityName: 'Osmaniye',
    cityNameEn: 'Osmaniye',
    damName: 'Aslantaş Barajı',
    damNameEn: 'Aslantas Dam',
    fullness: 54,
    weeklyChange: 0.1,
    monthlyChange: 2.3,
    yearlyChange: -2.1,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 320,
    lastUpdate: 'Canlı • 2 saat önce güncellendi'
  },
  {
    id: '17',
    cityName: 'Çanakkale',
    cityNameEn: 'Canakkale',
    damName: 'Atikhisar Barajı',
    damNameEn: 'Atikhisar Dam',
    fullness: 48,
    weeklyChange: -0.5,
    monthlyChange: -1.2,
    yearlyChange: -3.4,
    riskLevel: 'warning',
    droughtLabelTr: 'Hafif Kuraklık',
    droughtLabelEn: 'Light Drought',
    usableWater: 26.5,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  },
  {
    id: '81',
    cityName: 'Düzce',
    cityNameEn: 'Duzce',
    damName: 'Hasanlar Barajı',
    damNameEn: 'Hasanlar Dam',
    fullness: 68,
    weeklyChange: -0.3,
    monthlyChange: 1.2,
    yearlyChange: 5.1,
    riskLevel: 'safe',
    droughtLabelTr: 'Normal Seviye',
    droughtLabelEn: 'Normal Level',
    usableWater: 46.2,
    lastUpdate: 'Canlı • 1 saat önce güncellendi'
  }
];

export const REAL_PLATES_MAP: Record<string, string> = {
  'Adana': '01', 'Adıyaman': '02', 'Afyonkarahisar': '03', 'Ağrı': '04', 'Amasya': '05', 'Ankara': '06', 'Antalya': '07', 'Artvin': '08', 'Aydın': '09', 'Balıkesir': '10',
  'Bilecik': '11', 'Bingöl': '12', 'Bitlis': '13', 'Bolu': '14', 'Burdur': '15', 'Bursa': '16', 'Çanakkale': '17', 'Çankırı': '18', 'Çorum': '19', 'Denizli': '20',
  'Diyarbakır': '21', 'Edirne': '22', 'Elazığ': '23', 'Erzincan': '24', 'Erzurum': '25', 'Eskişehir': '26', 'Gaziantep': '27', 'Giresun': '28', 'Gümüşhane': '29', 'Hakkari': '30',
  'Hatay': '31', 'Isparta': '32', 'Mersin': '33', 'İstanbul': '34', 'İzmir': '35', 'Kars': '36', 'Kastamonu': '37', 'Kayseri': '38', 'Kırklareli': '39', 'Kırşehir': '40',
  'Kocaeli': '41', 'Konya': '42', 'Kütahya': '43', 'Malatya': '44', 'Manisa': '45', 'Kahramanmaraş': '46', 'Mardin': '47', 'Muğla': '48', 'Muş': '49', 'Nevşehir': '50',
  'Niğde': '51', 'Ordu': '52', 'Rize': '53', 'Sakarya': '54', 'Samsun': '55', 'Siirt': '56', 'Sinop': '57', 'Sivas': '58', 'Tekirdağ': '59', 'Tokat': '60',
  'Trabzon': '61', 'Tunceli': '62', 'Şanlıurfa': '63', 'Uşak': '64', 'Van': '65', 'Yozgat': '66', 'Zonguldak': '67', 'Aksaray': '68', 'Bayburt': '69', 'Karaman': '70',
  'Kırıkkale': '71', 'Batman': '72', 'Şırnak': '73', 'Bartın': '74', 'Ardahan': '75', 'Iğdır': '76', 'Yalova': '77', 'Karabük': '78', 'Kilis': '79', 'Osmaniye': '80',
  'Düzce': '81'
};

export const TURKEY_PROVINCES_DAMS: DamDetail[] = RAW_TURKEY_PROVINCES_DAMS.map(item => {
  const code = REAL_PLATES_MAP[item.cityName] || item.id;
  return {
    ...item,
    id: code
  };
}).sort((a, b) => parseInt(a.id) - parseInt(b.id));
